class Hadith {
  final String text;
  final String source;
  final String topic;
  final String textEn;
  final String sourceEn;
  final String topicEn;

  const Hadith(this.text, this.source, this.topic, this.textEn, this.sourceEn, this.topicEn);
}

// Kısa ve özlü hadisler; her vakitte farklı biri gösterilir.
// Kaynaklar: Buhârî ve Müslim (ağırlıklı), ayrıca Tirmizî, Ebû Dâvûd, İbn Mâce;
// birçoğu Nevevî'nin "Kırk Hadis"i ve "Riyâzü's-Sâlihîn"inde de yer alır.
// Türkçe ve İngilizce metinler bu uygulama için kaynaklardan serbest çeviridir
// ve yayından önce bir din görevlisi/ilim ehli tarafından gözden geçirilmelidir.
const List<Hadith> hadiths = [
  Hadith(
    "“Ameller niyetlere göredir. Herkes için yalnızca niyet ettiği şey vardır.”",
    "Buhârî, Müslim (Nevevî, Kırk Hadis 1)",
    "Niyet",
    "“Actions are judged by intentions, and everyone will have only what they intended.”",
    "Bukhari, Muslim (Nawawi, Forty Hadith 1)",
    "Intention",
  ),
  Hadith(
    "“Din, samimiyetle iyiliği istemektir (nasihattir).” “Kim için?” diye sorduk. “Allah için, Kitabı için, Resûlü için, Müslümanların yöneticileri ve bütün Müslümanlar için” buyurdu.",
    "Müslim (Nevevî, Kırk Hadis 7)",
    "Samimiyet",
    "“Religion is sincere goodwill (naseehah).” We asked, “For whom?” He said, “For Allah, His Book, His Messenger, the leaders of the Muslims and all Muslims.”",
    "Muslim (Nawawi, Forty Hadith 7)",
    "Sincerity",
  ),
  Hadith(
    "“Sizden biriniz, kendisi için istediğini kardeşi için de istemedikçe (gerçek anlamda) iman etmiş olmaz.”",
    "Buhârî, Müslim (Nevevî, Kırk Hadis 13)",
    "Kardeşlik",
    "“None of you truly believes until he loves for his brother what he loves for himself.”",
    "Bukhari, Muslim (Nawawi, Forty Hadith 13)",
    "Brotherhood",
  ),
  Hadith(
    "“Allah’a ve ahiret gününe inanan, ya hayır söylesin ya da sussun.”",
    "Buhârî, Müslim (Nevevî, Kırk Hadis 15)",
    "Söz",
    "“Whoever believes in Allah and the Last Day should speak good or keep silent.”",
    "Bukhari, Muslim (Nawawi, Forty Hadith 15)",
    "Speech",
  ),
  Hadith(
    "Bir adam Peygamberimizden nasihat istedi. “Öfkelenme” buyurdu. Adam isteğini birkaç defa tekrarladı; her seferinde “Öfkelenme” buyurdu.",
    "Buhârî (Nevevî, Kırk Hadis 16)",
    "Öfke",
    "A man asked the Prophet for advice. He said, “Do not become angry.” The man repeated his request several times, and each time he said, “Do not become angry.”",
    "Bukhari (Nawawi, Forty Hadith 16)",
    "Anger",
  ),
  Hadith(
    "“Müslüman, diğer Müslümanların elinden ve dilinden emin olduğu kimsedir.”",
    "Buhârî, Müslim",
    "Güven",
    "“A Muslim is one from whose tongue and hand other Muslims are safe.”",
    "Bukhari, Muslim",
    "Trust",
  ),
  Hadith(
    "“Güçlü kimse güreşte rakibini yenen değildir. Gerçek güçlü, öfkelendiği zaman kendine hâkim olandır.”",
    "Buhârî, Müslim",
    "Öfke · Nefis",
    "“The strong person is not the one who defeats others in wrestling, but the one who controls himself when angry.”",
    "Bukhari, Muslim",
    "Anger · Self-control",
  ),
  Hadith(
    "“Temizlik imanın yarısıdır.”",
    "Müslim",
    "Temizlik",
    "“Cleanliness is half of faith.”",
    "Muslim",
    "Cleanliness",
  ),
  Hadith(
    "“Güzel söz sadakadır.”",
    "Buhârî, Müslim",
    "Güzel Söz",
    "“A good word is charity.”",
    "Bukhari, Muslim",
    "Kind Words",
  ),
  Hadith(
    "“Kardeşine tebessüm etmen, senin için sadakadır.”",
    "Tirmizî",
    "Tebessüm",
    "“Your smile in the face of your brother is charity.”",
    "Tirmidhi",
    "Smiling",
  ),
  Hadith(
    "“İyilik, güzel ahlâktır. Günah ise içini rahatsız eden ve insanların bilmesini istemediğin şeydir.”",
    "Müslim (Nevevî, Kırk Hadis 27)",
    "Güzel Ahlâk",
    "“Righteousness is good character. Sin is what unsettles your heart and what you dislike people finding out.”",
    "Muslim (Nawawi, Forty Hadith 27)",
    "Good Character",
  ),
  Hadith(
    "“Nerede olursan ol Allah’a karşı gelmekten sakın. Kötülüğün ardından bir iyilik yap ki onu silsin. İnsanlara güzel ahlâkla davran.”",
    "Tirmizî (Nevevî, Kırk Hadis 18)",
    "Takvâ",
    "“Be mindful of Allah wherever you are. Follow a bad deed with a good one and it will erase it. Treat people with good character.”",
    "Tirmidhi (Nawawi, Forty Hadith 18)",
    "Taqwa",
  ),
  Hadith(
    "“Allah’ı gözet ki O da seni gözetsin. Bir şey istediğin zaman Allah’tan iste, yardım dilediğin zaman Allah’tan dile.”",
    "Tirmizî (Nevevî, Kırk Hadis 19)",
    "Tevekkül",
    "“Be mindful of Allah and He will protect you. When you ask, ask Allah; when you seek help, seek help from Allah.”",
    "Tirmidhi (Nawawi, Forty Hadith 19)",
    "Reliance on Allah",
  ),
  Hadith(
    "“Kişinin, kendisini ilgilendirmeyen şeyleri bırakması, Müslümanlığının güzelliğindendir.”",
    "Tirmizî (Nevevî, Kırk Hadis 12)",
    "Olgunluk",
    "“Part of the excellence of a person’s Islam is leaving what does not concern him.”",
    "Tirmidhi (Nawawi, Forty Hadith 12)",
    "Maturity",
  ),
  Hadith(
    "“Şüphe ettiğin şeyi bırak, şüphe etmediğin şeye bak.”",
    "Tirmizî, Nesâî (Nevevî, Kırk Hadis 11)",
    "Vera",
    "“Leave what makes you doubt for what does not make you doubt.”",
    "Tirmidhi, Nasa’i (Nawawi, Forty Hadith 11)",
    "Piety",
  ),
  Hadith(
    "“Zarar vermek de, zarara zararla karşılık vermek de yoktur.”",
    "İbn Mâce (Nevevî, Kırk Hadis 32)",
    "Adalet",
    "“There is to be no harm and no reciprocating harm.”",
    "Ibn Majah (Nawawi, Forty Hadith 32)",
    "Justice",
  ),
  Hadith(
    "“Kolaylaştırın, zorlaştırmayın; müjdeleyin, nefret ettirmeyin.”",
    "Buhârî, Müslim",
    "Kolaylık",
    "“Make things easy and do not make them difficult; give glad tidings and do not drive people away.”",
    "Bukhari, Muslim",
    "Ease",
  ),
  Hadith(
    "“Merhamet etmeyene merhamet edilmez.”",
    "Buhârî, Müslim",
    "Merhamet",
    "“He who does not show mercy will not be shown mercy.”",
    "Bukhari, Muslim",
    "Mercy",
  ),
  Hadith(
    "“Merhamet edenlere Rahmân merhamet eder. Yeryüzündekilere merhamet edin ki gökte olan size merhamet etsin.”",
    "Ebû Dâvûd, Tirmizî",
    "Merhamet",
    "“The Most Merciful shows mercy to those who are merciful. Be merciful to those on earth and the One above the heavens will be merciful to you.”",
    "Abu Dawud, Tirmidhi",
    "Mercy",
  ),
  Hadith(
    "“Müminler, birbirlerini sevmekte, esirgemekte ve acımakta bir vücut gibidir. Bir uzvu rahatsızlandığında diğer uzuvlar da uykusuzluk ve ateşle ona katılır.”",
    "Buhârî, Müslim",
    "Dayanışma",
    "“The believers, in their love, mercy and compassion for one another, are like one body: when one part suffers, the whole body responds with sleeplessness and fever.”",
    "Bukhari, Muslim",
    "Solidarity",
  ),
  Hadith(
    "“Mümin, mümine karşı, parçaları birbirini destekleyen bir bina gibidir.” Sonra parmaklarını birbirine kenetledi.",
    "Buhârî, Müslim",
    "Birlik",
    "“The believer to the believer is like a building whose parts support one another.” Then he interlaced his fingers.",
    "Bukhari, Muslim",
    "Unity",
  ),
  Hadith(
    "“İki nimet vardır ki insanların çoğu bunlar konusunda aldanmıştır: sağlık ve boş vakit.”",
    "Buhârî",
    "Zaman · Sağlık",
    "“There are two blessings which many people lose out on: health and free time.”",
    "Bukhari",
    "Time · Health",
  ),
  Hadith(
    "“Dünyada bir garip, hatta bir yolcu gibi ol.”",
    "Buhârî (Nevevî, Kırk Hadis 40)",
    "Dünya",
    "“Be in this world as if you were a stranger or a traveler.”",
    "Bukhari (Nawawi, Forty Hadith 40)",
    "This World",
  ),
  Hadith(
    "“Sadaka malı eksiltmez. Allah, affeden kulunun izzetini artırır. Allah için alçak gönüllü olanı Allah yüceltir.”",
    "Müslim",
    "Cömertlik · Tevazu",
    "“Charity does not decrease wealth. Allah increases the honor of one who forgives, and raises the one who humbles himself for Allah’s sake.”",
    "Muslim",
    "Generosity · Humility",
  ),
  Hadith(
    "“Allah güzeldir, güzeli sever. Kibir, hakkı reddetmek ve insanları küçük görmektir.”",
    "Müslim",
    "Kibir",
    "“Allah is beautiful and loves beauty. Arrogance is rejecting the truth and looking down on people.”",
    "Muslim",
    "Arrogance",
  ),
  Hadith(
    "“Allah sizin suretlerinize ve mallarınıza bakmaz; kalplerinize ve amellerinize bakar.”",
    "Müslim",
    "Kalp · Amel",
    "“Allah does not look at your appearance or your wealth, but He looks at your hearts and your deeds.”",
    "Muslim",
    "Heart · Deeds",
  ),
  Hadith(
    "“Kim hayra vesile olursa, o hayrı yapanın ecri gibi ecir alır.”",
    "Müslim",
    "Hayra Vesile Olmak",
    "“Whoever guides someone to good will have a reward like the one who does it.”",
    "Muslim",
    "Guiding to Good",
  ),
  Hadith(
    "“İnsan ölünce ameli kesilir; ancak üç şey hariç: sürekli sadaka, faydalanılan ilim ve kendisine dua eden hayırlı evlat.”",
    "Müslim",
    "Sadaka-i Câriye",
    "“When a person dies, his deeds end except three: ongoing charity, beneficial knowledge, and a righteous child who prays for him.”",
    "Muslim",
    "Ongoing Charity",
  ),
  Hadith(
    "“Sizin en hayırlınız, Kur’an’ı öğrenen ve öğretendir.”",
    "Buhârî",
    "Kur’an",
    "“The best among you are those who learn the Quran and teach it.”",
    "Bukhari",
    "The Quran",
  ),
  Hadith(
    "“Kim ilim öğrenmek için bir yola girerse, Allah ona cennete giden bir yolu kolaylaştırır.”",
    "Müslim",
    "İlim",
    "“Whoever treads a path seeking knowledge, Allah makes easy for him a path to Paradise.”",
    "Muslim",
    "Knowledge",
  ),
  Hadith(
    "“Kim bir müminin dünya sıkıntılarından birini giderirse, Allah da onun kıyamet günü sıkıntılarından birini giderir.”",
    "Müslim (Nevevî, Kırk Hadis 36)",
    "Yardımlaşma",
    "“Whoever relieves a believer of a worldly hardship, Allah will relieve him of a hardship on the Day of Resurrection.”",
    "Muslim (Nawawi, Forty Hadith 36)",
    "Helping Others",
  ),
  Hadith(
    "“Allah’a ve ahiret gününe inanan, komşusuna ikramda bulunsun.”",
    "Buhârî, Müslim",
    "Komşuluk",
    "“Whoever believes in Allah and the Last Day should be generous to his neighbor.”",
    "Bukhari, Muslim",
    "Neighbors",
  ),
  Hadith(
    "“Müslümanın Müslüman üzerindeki hakkı beştir: selamını almak, hastayı ziyaret etmek, cenazesine katılmak, davetine icabet etmek ve aksırdığında ‘Yerhamükellah’ demek.”",
    "Buhârî, Müslim",
    "Haklar",
    "“A Muslim has five rights over another Muslim: returning his greeting, visiting him when sick, attending his funeral, accepting his invitation, and responding to his sneeze.”",
    "Bukhari, Muslim",
    "Rights",
  ),
  Hadith(
    "“Birbirinizi sevmedikçe iman etmiş olmazsınız. Yaptığınız takdirde birbirinizi seveceğiniz bir şeyi size söyleyeyim mi? Aranızda selamı yayın.”",
    "Müslim",
    "Selam",
    "“You will not believe until you love one another. Shall I tell you something that will make you love one another? Spread the greeting of peace among yourselves.”",
    "Muslim",
    "Greeting of Peace",
  ),
  Hadith(
    "“Kim sabah namazını kılarsa Allah’ın korumasındadır.”",
    "Müslim",
    "Sabah Namazı",
    "“Whoever prays the dawn prayer is under Allah’s protection.”",
    "Muslim",
    "Dawn Prayer",
  ),
  Hadith(
    "“Sabah namazının iki rekât sünneti, dünyadan ve dünyadaki her şeyden daha hayırlıdır.”",
    "Müslim",
    "Sabah Sünneti",
    "“The two rak‘ahs before the dawn prayer are better than the world and everything in it.”",
    "Muslim",
    "Dawn Sunnah",
  ),
  Hadith(
    "“Kim yatsı namazını cemaatle kılarsa gecenin yarısını ibadetle geçirmiş gibidir. Kim sabah namazını da cemaatle kılarsa gecenin tamamını ibadetle geçirmiş gibidir.”",
    "Müslim",
    "Yatsı · Cemaat",
    "“Whoever prays the night prayer in congregation is as if he stood half the night in prayer; and whoever also prays the dawn prayer in congregation is as if he prayed the whole night.”",
    "Muslim",
    "Night Prayer · Congregation",
  ),
  Hadith(
    "“Kim ikindi namazını terk ederse ameli boşa gitmiştir.”",
    "Buhârî",
    "İkindi Namazı",
    "“Whoever abandons the afternoon prayer, his deeds are in vain.”",
    "Bukhari",
    "Afternoon Prayer",
  ),
  Hadith(
    "“Beş vakit namaz, büyük günahlardan kaçınıldığı sürece, aralarındaki günahlara kefarettir.”",
    "Müslim",
    "Beş Vakit Namaz",
    "“The five daily prayers expiate the sins between them, as long as major sins are avoided.”",
    "Muslim",
    "Five Daily Prayers",
  ),
  Hadith(
    "“Birinizin kapısı önünde bir nehir olsa ve her gün beş defa yıkansa, üzerinde kir kalır mı?” “Hayır” dediler. “İşte beş vakit namaz da böyledir; Allah onunla hataları siler” buyurdu.",
    "Buhârî, Müslim",
    "Namaz",
    "“If one of you had a river at his door and bathed in it five times a day, would any dirt remain on him?” They said no. He said, “That is like the five prayers; Allah erases sins through them.”",
    "Bukhari, Muslim",
    "Prayer",
  ),
  Hadith(
    "“Allah’a en sevimli amel hangisidir?” diye sordum. “Vaktinde kılınan namaz” buyurdu. “Sonra hangisi?” dedim. “Anne babaya iyilik” buyurdu.",
    "Buhârî, Müslim",
    "Vaktinde Namaz",
    "I asked, “Which deed is most beloved to Allah?” He said, “Prayer at its proper time.” I asked, “Then which?” He said, “Kindness to parents.”",
    "Bukhari, Muslim",
    "Prayer on Time",
  ),
  Hadith(
    "“Dua, ibadetin ta kendisidir.”",
    "Ebû Dâvûd, Tirmizî",
    "Dua",
    "“Supplication is worship itself.”",
    "Abu Dawud, Tirmidhi",
    "Supplication",
  ),
  Hadith(
    "“Allah’ın en çok sevdiği amel, az da olsa devamlı olanıdır.”",
    "Buhârî, Müslim",
    "Devamlılık",
    "“The most beloved deed to Allah is the most consistent, even if it is small.”",
    "Bukhari, Muslim",
    "Consistency",
  ),
  Hadith(
    "“Günahtan tövbe eden, hiç günahı olmayan gibidir.”",
    "İbn Mâce",
    "Tövbe",
    "“One who repents from sin is like one who has no sin.”",
    "Ibn Majah",
    "Repentance",
  ),
  Hadith(
    "“Ey Âdemoğlu! Beni çağırdığın ve bana umut bağladığın sürece, günahların ne olursa olsun seni bağışlarım.”",
    "Tirmizî (Nevevî, Kırk Hadis 42)",
    "Af",
    "“O son of Adam, as long as you call upon Me and hope in Me, I will forgive you regardless of what you have done.”",
    "Tirmidhi (Nawawi, Forty Hadith 42)",
    "Forgiveness",
  ),
  Hadith(
    "“Doğru sözlü olun. Çünkü doğruluk iyiliğe, iyilik de cennete götürür.”",
    "Buhârî, Müslim",
    "Doğruluk",
    "“Hold to truthfulness, for truthfulness leads to righteousness, and righteousness leads to Paradise.”",
    "Bukhari, Muslim",
    "Truthfulness",
  ),
  Hadith(
    "“Münafığın alâmeti üçtür: Konuşunca yalan söyler, söz verince sözünden döner, kendisine güvenilince emanete hıyanet eder.”",
    "Buhârî, Müslim",
    "Emanet · Söz",
    "“The signs of a hypocrite are three: when he speaks he lies, when he promises he breaks it, and when trusted he betrays.”",
    "Bukhari, Muslim",
    "Trust · Promises",
  ),
  Hadith(
    "“Hayâ ancak hayır getirir.”",
    "Buhârî, Müslim",
    "Hayâ",
    "“Modesty brings nothing but good.”",
    "Bukhari, Muslim",
    "Modesty",
  ),
  Hadith(
    "“Kıyamet günü mizanda en ağır gelecek şey güzel ahlâktır.”",
    "Tirmizî, Ebû Dâvûd",
    "Güzel Ahlâk",
    "“Nothing will be heavier on the Scale on the Day of Resurrection than good character.”",
    "Tirmidhi, Abu Dawud",
    "Good Character",
  ),
  Hadith(
    "“Müminlerin iman bakımından en olgunu, ahlâkı en güzel olanıdır.”",
    "Tirmizî, Ebû Dâvûd",
    "Güzel Ahlâk",
    "“The believers with the most complete faith are those with the best character.”",
    "Tirmidhi, Abu Dawud",
    "Good Character",
  ),
  Hadith(
    "“İyi davranmaya en layık kişi annendir, sonra annendir, sonra annendir, sonra babandır.”",
    "Buhârî, Müslim",
    "Ana Baba",
    "“The one most deserving of your good company is your mother, then your mother, then your mother, then your father.”",
    "Bukhari, Muslim",
    "Parents",
  ),
  Hadith(
    "“Rabbini zikredenle zikretmeyenin misali, diri ile ölü gibidir.”",
    "Buhârî",
    "Zikir",
    "“The example of one who remembers his Lord and one who does not is like the living and the dead.”",
    "Bukhari",
    "Remembrance",
  ),
  Hadith(
    "“Dile hafif, mizanda ağır, Rahmân’a sevimli iki kelime vardır: Sübhânallâhi ve bihamdihî, Sübhânallâhi’l-azîm.”",
    "Buhârî, Müslim",
    "Tesbih",
    "“There are two phrases light on the tongue, heavy on the Scale, beloved to the Most Merciful: Subhan Allahi wa bihamdihi, Subhan Allahil-‘Azim.”",
    "Bukhari, Muslim",
    "Glorification",
  ),
  Hadith(
    "“Güneşin doğduğu her gün, insanın her bir eklemi için bir sadaka vardır. İki kişi arasında adaleti sağlaman da sadakadır.”",
    "Buhârî, Müslim (Nevevî, Kırk Hadis 26)",
    "Sadaka",
    "“Every joint of a person owes charity each day the sun rises. Bringing justice between two people is charity.”",
    "Bukhari, Muslim (Nawawi, Forty Hadith 26)",
    "Charity",
  ),
  Hadith(
    "“Bir Müslüman bir ağaç diker ya da ekin eker de ondan bir insan, kuş veya hayvan yerse, bu onun için sadaka olur.”",
    "Buhârî, Müslim",
    "Hayır",
    "“If a Muslim plants a tree or sows a crop and a person, bird or animal eats from it, it is charity for him.”",
    "Bukhari, Muslim",
    "Good Deeds",
  ),
  Hadith(
    "“Sabır, musibetin ilk sarsıntısı anındadır.”",
    "Buhârî, Müslim",
    "Sabır",
    "“Patience is at the first strike of calamity.”",
    "Bukhari, Muslim",
    "Patience",
  ),
  Hadith(
    "“Müminin durumu ne şaşırtıcıdır! Her hâli onun için hayırdır: Sevindiğinde şükreder, bu onun için hayır olur; sıkıntıya uğradığında sabreder, bu da onun için hayır olur.”",
    "Müslim",
    "Şükür · Sabır",
    "“How wonderful is the affair of the believer! All of it is good: if good befalls him he is grateful, and that is good for him; if hardship befalls him he is patient, and that is good for him.”",
    "Muslim",
    "Gratitude · Patience",
  ),
  Hadith(
    "“Zandan sakının; çünkü zan, sözlerin en yalanıdır.”",
    "Buhârî, Müslim",
    "Zan",
    "“Beware of suspicion, for suspicion is the most false of speech.”",
    "Bukhari, Muslim",
    "Suspicion",
  ),
  Hadith(
    "“Birbirinize haset etmeyin, kin tutmayın, sırt çevirmeyin. Ey Allah’ın kulları, kardeş olun.”",
    "Buhârî, Müslim",
    "Kardeşlik",
    "“Do not envy one another, do not hold grudges, do not turn away from one another. O servants of Allah, be brothers.”",
    "Bukhari, Muslim",
    "Brotherhood",
  ),
  Hadith(
    "“Bir Müslüman, Müslüman kardeşini ziyaret ettiği sürece, dönünceye kadar cennet meyvelerinin içindedir.”",
    "Müslim",
    "Ziyaret",
    "“A Muslim who visits his Muslim brother remains in the fruit-gathering of Paradise until he returns.”",
    "Muslim",
    "Visiting",
  ),
  Hadith(
    "“İnsanlara teşekkür etmeyen, Allah’a şükretmiş olmaz.”",
    "Ebû Dâvûd, Tirmizî",
    "Şükür",
    "“Whoever does not thank people has not thanked Allah.”",
    "Abu Dawud, Tirmidhi",
    "Gratitude",
  ),
  Hadith(
    "“Mümin; ta’n eden, lânet eden, kötü sözlü ve ağzı bozuk olan değildir.”",
    "Tirmizî",
    "Dil",
    "“The believer is not one who slanders, curses, or speaks obscenely or rudely.”",
    "Tirmidhi",
    "The Tongue",
  ),
];

/// [day] gün sayısı, [prayerIndex] vakit sırası (0 imsak … 5 yatsı) olmak üzere o vaktin hadisi.
/// Aynı vakit içinde sabit kalır; her vakitte ve her günde başka bir hadise geçer.
/// Sıra, listedeki dizilişi değil karıştırılmış bir dizilişi izler; liste bitmeden tekrar etmez.
Hadith hadithForPrayer(int day, int prayerIndex) {
  const stride = 17; // hadiths.length ile aralarında asal olmalıdır
  final n = hadiths.length;
  assert(_gcd(stride, n) == 1, 'stride, hadiths.length ile aralarında asal olmalı');
  final slot = day * 6 + prayerIndex;
  return hadiths[(slot * stride) % n];
}

int _gcd(int a, int b) => b == 0 ? a : _gcd(b, a % b);
