class Hadith {
  final String text;
  final String source;
  final String topic;
  final String textEn;
  final String sourceEn;
  final String topicEn;

  const Hadith(this.text, this.source, this.topic, this.textEn, this.sourceEn, this.topicEn);
}

// Kaynak: T.C. Diyanet İşleri Başkanlığı, Din Hizmetleri Genel Müdürlüğü,
// "Hadis-i Şerif Metinleri" (2022).
const List<Hadith> hadiths = [
  Hadith(
    "Câbir’den nakledildiğine göre, Resûlullah (sav) insanlara hitap ederken önce lâyık-ı vechile Allah’a hamd ve senâ eder, sonra da “Bir kimseye Allah hidayet verirse artık onu saptıracak yoktur; Allah’ın saptırdığına da hidayet verecek yoktur. Sözün en hayırlısı Allah’ın Kitabı’dır.” buyururdu.",
    "Müslim, Cum’a, 45",
    "İman · Hidayet",
    "It is narrated from Jabir that when the Messenger of Allah (peace be upon him) addressed the people, he would first praise and glorify Allah as He deserves, and then say: “Whomever Allah guides, none can lead astray; and whomever Allah leads astray, none can guide. The best of speech is the Book of Allah.”",
    "Muslim, Cum’a, 45",
    "Faith · Guidance",
  ),
  Hadith(
    "İbn Ömer’in naklettiğine göre, Resûlullah (sav) şöyle buyurmuştur: “İslâm beş esas üzerine kurulmuştur: Allah’tan başka ilâh olmadığına ve Muhammed’in Allah’ın Resûlü olduğuna şehâdet etmek, namaz kılmak, zekât vermek, haccetmek ve Ramazan orucunu tutmak.”",
    "Buhârî, Îmân, 2",
    "İman · İslam",
    "Ibn Umar narrated that the Messenger of Allah (peace be upon him) said: “Islam is built upon five pillars: bearing witness that there is no god but Allah and that Muhammad is the Messenger of Allah, establishing the prayer, giving zakat, performing the Hajj, and fasting in Ramadan.”",
    "Bukhari, Îmân, 2",
    "Faith · Islam",
  ),
  Hadith(
    "Enes (b. Mâlik) tarafından nakledildiğine göre, Hz. Peygamber (sav) şöyle buyurmuştur: “Şu üç özellik kimde bulunursa o kimse imanın tadını alır: Allah ve Resûlü’nü her şeyden çok sevmek, bir kimseyi yalnızca Allah rızası için sevmek, Allah kendisini kurtardıktan sonra tekrar inkârcılığa dönmekten ateşe atılmaktan kaçındığı gibi kaçınmak.”",
    "Müslim, Îmân, 67",
    "İman · İmanın Tadı",
    "It is narrated from Anas (ibn Malik) that the Prophet (peace be upon him) said: “Whoever has these three qualities will taste the sweetness of faith: loving Allah and His Messenger more than anything else; loving a person solely for the sake of Allah; and hating to return to disbelief after Allah has saved him from it, just as he would hate to be thrown into the Fire.”",
    "Muslim, Îmân, 67",
    "Faith · The Sweetness of Faith",
  ),
  Hadith(
    "Ebû Hüreyre’den rivayet edildiğine göre, Allah Resûlü (sav) şöyle buyurmuştur: “İmanın yetmiş küsur şubesi vardır. Bunların en üstünü “Lâ ilâhe illâllâh” (Allah’tan başka ilâh yoktur.) sözüdür. En alt derecesi ise yoldaki eziyet veren şeyleri kaldırmaktır. Hayâ da imanın bir şubesidir.”",
    "Nesâî, Îmân, 16; Müslim, Îmân, 58",
    "İman · İmanın Şubeleri",
    "It is narrated from Abu Hurairah that the Messenger of Allah (peace be upon him) said: “Faith has seventy-some branches. The highest of them is the saying ‘La ilaha illallah’ (There is no god but Allah), and the lowest is removing something harmful from the road. Modesty (haya) is also a branch of faith.”",
    "Nasa'i, Îmân, 16; Muslim, Îmân, 58",
    "Faith · The Branches of Faith",
  ),
  Hadith(
    "Ebû Hüreyre’nin rivayet ettiğine göre, Resûlullah (sav) şöyle dua ederdi: “Allah’ım! Bozgunculuktan, münafıklıktan ve kötü ahlâktan sana sığınırım.”",
    "Ebû Dâvûd, Vitr, 32",
    "İman · Allah’a Sığınmak",
    "Abu Hurairah narrated that the Messenger of Allah (peace be upon him) used to supplicate: “O Allah! I seek refuge in You from discord, from hypocrisy, and from bad character.”",
    "Abu Dawud, Vitr, 32",
    "Faith · Seeking Refuge in Allah",
  ),
  Hadith(
    "Hz. Âişe’den nakledildiğine göre, Peygamber (sav) şöyle demiştir: “Kur’an’ı ezberleyip okuyan kişi, Allah katındaki seçkin meleklerle birlikte olacaktır. Kur’an’ı zorlanarak da olsa devamlı okumaya çalışan kişiye ise iki kat ecir vardır.”",
    "Buhârî, Tefsîr, (Abese) 1",
    "İman · Kur’an-ı Kerim Tilaveti",
    "It is narrated from Aisha that the Prophet (peace be upon him) said: “The one who memorizes and recites the Quran will be with the noble, honored angels in the presence of Allah. And the one who strives to recite the Quran regularly, even though it is difficult for him, will have a double reward.”",
    "Bukhari, Tefsîr, (Abese) 1",
    "Faith · Reciting the Holy Quran",
  ),
  Hadith(
    "Ebû Hüreyre’den nakledildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Ben dünyada ve âhirette Meryem oğlu İsa’ya insanların en yakın olanıyım. Peygamberler, ataları bir, anneleri ayrı kardeştirler. Dinleri ise tektir.”",
    "Buhârî, Enbiyâ, 48",
    "İman · Peygamberlere İman",
    "It is narrated from Abu Hurairah that the Messenger of Allah (peace be upon him) said: “I am the closest of people to Jesus, son of Mary, in this world and in the Hereafter. The prophets are brothers with one father and different mothers; their religion is one.”",
    "Bukhari, Enbiyâ, 48",
    "Faith · Belief in the Prophets",
  ),
  Hadith(
    "Ebû Hüreyre’den rivayet edildiğine göre, Resûlullah (sav) cuma gününden bahsederek şöyle buyurmuştur: “Onda öyle bir an vardır ki şayet bir Müslüman namaz kılarken o âna rastlar da Allah’tan bir şey isterse Allah, ona dilediğini mutlaka verir.”",
    "Müslim, Cum’a, 13",
    "İbadet · Cuma Namazı",
    "It is narrated from Abu Hurairah that the Messenger of Allah (peace be upon him), speaking about Friday, said: “There is an hour in it such that if a Muslim happens upon it while praying and asks Allah for something, Allah will surely grant him what he asks.”",
    "Muslim, Cum’a, 13",
    "Worship · Friday Prayer",
  ),
  Hadith(
    "Abdullah (b. Mes’ûd) tarafından nakledildiğine göre, Allah Resûlü (sav) şöyle buyurmuştur: “Günahtan tevbe etmek, günahı terk edip bir daha ona dönmemektir.”",
    "İbn Hanbel, I, 446",
    "İbadet · Tevbe",
    "It is narrated from Abdullah (ibn Mas'ud) that the Messenger of Allah (peace be upon him) said: “Repentance from a sin is to abandon the sin and never return to it again.”",
    "Ahmad ibn Hanbal, I, 446",
    "Worship · Repentance",
  ),
  Hadith(
    "Muâz b. Cebel’den nakledildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Lânetlenmeye neden olan üç şeyi yapmaktan sakının; su kaynaklarının çevresine, yol ortasına ve gölgelik yerlere abdest bozmaktan.”",
    "Ebû Dâvûd, Tahâret, 14",
    "İbadet · Hacet Gidermede Dikkat Edilecek Hususlar",
    "It is narrated from Muadh ibn Jabal that the Messenger of Allah (peace be upon him) said: “Beware of the three things that bring curses: relieving oneself near water sources, in the middle of the road, and in shaded places.”",
    "Abu Dawud, Tahâret, 14",
    "Worship · Etiquette of Relieving Oneself",
  ),
  Hadith(
    "Ebû Hüreyre’den nakledildiğine göre, Hz. Peygamber (sav) şöyle buyurmuştur: “Her yedi günde bir yıkanmak, Yüce Allah’ın her Müslüman üzerindeki hakkıdır.”",
    "Buhârî, Cum’a, 12",
    "İbadet · Beden Temizliği",
    "It is narrated from Abu Hurairah that the Prophet (peace be upon him) said: “It is a right of Allah the Exalted upon every Muslim that he bathe once every seven days.”",
    "Bukhari, Cum’a, 12",
    "Worship · Bodily Cleanliness",
  ),
  Hadith(
    "(Hz. Peygamber’e vahiy kâtipliği yapan) Hanzala (b. Rebî’) Kâtib anlatıyor: Allah Resûlü’nü (sav) şöyle derken işittim: “Rükûları, secdeleri, abdestleri ve vakitlerine riayet ederek beş vakit namaz(ı kılmay)a devam eden ve bu beş vakit namazın Allah katından gelen bir emr-i hak olduğunu kabul eden kimse cennete girer.”",
    "İbn Hanbel, IV, 266",
    "İbadet · Beş Vakit Namaz",
    "Hanzala (ibn Rabi') al-Katib (who served as a scribe of revelation for the Prophet) narrates: I heard the Messenger of Allah (peace be upon him) say: “Whoever keeps up the five daily prayers, observing their bowings, prostrations, ablutions and times, and accepts that these five prayers are a true command from Allah, will enter Paradise.”",
    "Ahmad ibn Hanbal, IV, 266",
    "Worship · The Five Daily Prayers",
  ),
  Hadith(
    "Ebû Hüreyre’den rivayet edildiğine göre, Allah Resûlü (sav) şöyle buyurmuştur: “Kulun Rabbine en yakın olduğu (an) secde hâlidir. Öyleyse (secdede iken) çokça dua ediniz.”",
    "Müslim, Salât, 215",
    "İbadet · Secde",
    "It is narrated from Abu Hurairah that the Messenger of Allah (peace be upon him) said: “The closest a servant comes to his Lord is when he is in prostration. So make abundant supplication (while prostrating).”",
    "Muslim, Salât, 215",
    "Worship · Prostration",
  ),
  Hadith(
    "Ebû Hüreyre’den rivayet edildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Müminlerin iman bakımından en mükemmeli, ahlâk bakımından en güzel olanıdır.”",
    "Ebû Dâvûd, Sünnet, 15",
    "Güzel Ahlak · İman ve Ahlak",
    "It is narrated from Abu Hurairah that the Messenger of Allah (peace be upon him) said: “The most perfect of the believers in faith is the one who is best in character.”",
    "Abu Dawud, Sünnet, 15",
    "Good Character · Faith and Character",
  ),
  Hadith(
    "Ebû Hüreyre’den nakledildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Allah sizin suretlerinize ve mallarınıza bakmaz, ancak kalplerinize ve amellerinize bakar.”",
    "Müslim, Birr, 34",
    "Güzel Ahlak · Kalp ve Amel",
    "It is narrated from Abu Hurairah that the Messenger of Allah (peace be upon him) said: “Allah does not look at your appearances or your wealth; rather, He looks at your hearts and your deeds.”",
    "Muslim, Birr, 34",
    "Good Character · The Heart and Deeds",
  ),
  Hadith(
    "Esed kabilesine mensup Vâbisa b. Ma’bed, Resûlullah’ın (sav) kendisine şöyle dediğini nakletmiştir: “… İyilik, gönlü huzura kavuşturan ve içe sinen şeydir; kötülük ise, insanlar sana fetva verseler (onaylasalar) bile, gönlü(nü) huzursuz eden ve iç(in)de bir kuşku bırakan şeydir.”",
    "Dârimî, Büyû’, 2",
    "Güzel Ahlak · İyilik ve Kötülük",
    "Wabisa ibn Ma'bad, of the tribe of Asad, narrated that the Messenger of Allah (peace be upon him) said to him: “… Goodness is that which brings peace to the heart and settles comfortably within; evil is that which unsettles the heart and leaves doubt within you, even if people give you a ruling (approving it).”",
    "Darimi, Büyû’, 2",
    "Good Character · Good and Evil",
  ),
  Hadith(
    "Ebû Zer’den rivayet edildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Amellerin en faziletlisi Allah için sevmek ve Allah için nefret etmektir.”",
    "Ebû Dâvûd, Sünnet, 2",
    "Güzel Ahlak · Allah İçin Sevmek",
    "It is narrated from Abu Dharr that the Messenger of Allah (peace be upon him) said: “The most virtuous of deeds is to love for the sake of Allah and to hate for the sake of Allah.”",
    "Abu Dawud, Sünnet, 2",
    "Good Character · Loving for Allah's Sake",
  ),
  Hadith(
    "Nu’mân b. Beşîr’in naklettiğine göre Resûlullah (sav) şöyle buyurmuştur: “Müminler, birbirlerini sevmede, birbirlerine merhamet ve şefkat göstermede, tıpkı bir organı rahatsızlandığında diğer organları da uykusuzluk ve yüksek ateşle bu acıyı paylaşan bir bedene benzer.”",
    "Müslim, Birr, 66; Buhârî, Edeb, 27",
    "Güzel Ahlak · Mümin Kardeşliği",
    "Nu'man ibn Bashir narrated that the Messenger of Allah (peace be upon him) said: “In their mutual love, mercy and compassion, the believers are like a single body: when one organ of it is ailing, the rest of the body shares its pain with sleeplessness and fever.”",
    "Muslim, Birr, 66; Bukhari, Edeb, 27",
    "Good Character · Brotherhood of Believers",
  ),
  Hadith(
    "Enes (b. Mâlik)’ten rivayet edildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Arsızlık nerede ve kimde olursa olsun çirkinleştirir; hayâ ise nerede ve kimde olursa olsun zarifleştirir”",
    "Tirmizî, Birr, 47",
    "Güzel Ahlak · Hayâ",
    "It is narrated from Anas (ibn Malik) that the Messenger of Allah (peace be upon him) said: “Shamelessness disfigures whatever it is found in and whoever has it; modesty adorns whatever it is found in and whoever has it.”",
    "Tirmidhi, Birr, 47",
    "Good Character · Modesty",
  ),
  Hadith(
    "Ebû Hüreyre’den (ra) nakledildiğine göre, Hz. Peygamber (sav) şöyle buyurmuştur: “Bir kadınla dört şeyden dolayı evlenilir: Malı, soyu, güzelliği ve dini için. Sen dindar olanını seç. (Aksi hâlde) fakr u zarurete duçar olursun!”",
    "Buhârî, Nikâh, 16",
    "Sosyal Hayat · Evlilik",
    "It is narrated from Abu Hurairah (may Allah be pleased with him) that the Prophet (peace be upon him) said: “A woman is married for four things: her wealth, her lineage, her beauty and her religion. Choose the one who is religious. (Otherwise) you will be reduced to poverty and want!”",
    "Bukhari, Nikâh, 16",
    "Social Life · Marriage",
  ),
  Hadith(
    "Sevbân’dan nakledildiğine göre, Hz. Peygamber (sav) şöyle buyurmuştur: “Hiç kimsenin izinsiz olarak bir başkasının evinin içine bakması helâl değildir. Eğer bakarsa (eve) girmiş demektir...”",
    "Tirmizî, Salât, 148; İbn Hanbel, V, 280",
    "Sosyal Hayat · Mahremiyet",
    "It is narrated from Thawban that the Prophet (peace be upon him) said: “It is not permissible for anyone to look inside another person's house without permission. If he looks, it is as if he has entered (the house)...”",
    "Tirmidhi, Salât, 148; Ahmad ibn Hanbal, V, 280",
    "Social Life · Privacy",
  ),
  Hadith(
    "Ebu’d-Derdâ’nın naklettiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Muhakkak ki siz kıyamet günü isimlerinizle ve babalarınızın isimleriyle çağrılacaksınız. O hâlde (çocuklarınıza) güzel isimler koyun.”",
    "Ebû Dâvûd, Edeb, 61",
    "Sosyal Hayat · İsim Koyma",
    "Abu al-Darda narrated that the Messenger of Allah (peace be upon him) said: “Indeed, on the Day of Resurrection you will be called by your names and the names of your fathers. So give (your children) good names.”",
    "Abu Dawud, Edeb, 61",
    "Social Life · Naming",
  ),
  Hadith(
    "Ebû Hüreyre’nin naklettiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Mümin, hanımına karşı kötü duygular beslemesin; çünkü onun bazı huylarından hoşlanmasa da diğer huylarından hoşlanabilir.”",
    "Müslim, Radâ’, 61",
    "Sosyal Hayat · Aile İçi İletişim",
    "Abu Hurairah narrated that the Messenger of Allah (peace be upon him) said: “A believer should not harbor ill feelings toward his wife; for even if he dislikes some of her traits, he may be pleased with others.”",
    "Muslim, Radâ’, 61",
    "Social Life · Communication Within the Family",
  ),
  Hadith(
    "İbn Ömer’den rivayet edildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Allah’ın kadın kullarının Allah’ın mescitlerine gelmelerine engel olmayın.”",
    "Müslim, Salât, 136",
    "Sosyal Hayat · Kadın, Cami ve Cemaat",
    "It is narrated from Ibn Umar that the Messenger of Allah (peace be upon him) said: “Do not prevent the female servants of Allah from coming to the mosques of Allah.”",
    "Muslim, Salât, 136",
    "Social Life · Women, the Mosque and Congregation",
  ),
  Hadith(
    "Enes b. Mâlik (ra) diyor ki: Ben Hz. Peygamber’in (sav) şöyle buyurduğunu işittim: “Yüce Allah, “İki sevgilisi (olan gözlerini almak sureti) ile kulumu sınadığımda sabrederse, bu ikisine karşılık ona cenneti veririm.” buyurdu.”",
    "Buhârî, Merdâ, 7",
    "Sosyal Hayat · Engellilik ve Sabır",
    "Anas ibn Malik (may Allah be pleased with him) said: I heard the Prophet (peace be upon him) say: “Allah the Exalted said: ‘When I test My servant through his two beloved ones (by taking his eyes) and he remains patient, I will give him Paradise in return for them.’”",
    "Bukhari, Merdâ, 7",
    "Social Life · Disability and Patience",
  ),
  Hadith(
    "Ebû Hüreyre’den nakledildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Ümmetimin hepsi cennete girecektir, yüz çeviren müstesna!” Orada bulunanlar “Ey Allah’ın Resûlü, yüz çeviren kim?” diye sorunca, Hz. Peygamber, “Bana itaat eden cennete girer. Bana isyan eden yüz çevirmiş demektir.” şeklinde cevap vermiştir.",
    "Buhârî, İ’tisâm, 2",
    "İman · Peygambere İtaat",
    "It is narrated from Abu Hurairah that the Messenger of Allah (peace be upon him) said: “All of my community will enter Paradise, except the one who turns away!” Those present asked, “O Messenger of Allah, who is the one who turns away?” The Prophet (peace be upon him) replied, “Whoever obeys me will enter Paradise. Whoever disobeys me has turned away.”",
    "Bukhari, İ’tisâm, 2",
    "Faith · Obeying the Prophet",
  ),
  Hadith(
    "Ebû Hüreyre’den Resûlullah’ın (sav) şöyle dediği nakledilmiştir: “Muhammed’in canını elinde tutan Allah’a yemin ederim ki bu ümmetten bir Yahudi veya Hıristiyan beni işitir, sonra da benim kendisiyle gönderildiğim (vahy)e iman etmeden ölürse mutlaka ateş ehlinden olur.”",
    "Müslim, Îmân, 240",
    "İman · Peygamberi Tasdik Etmek",
    "It is narrated from Abu Hurairah that the Messenger of Allah (peace be upon him) said: “I swear by Allah, in whose hand is the soul of Muhammad, that any Jew or Christian of this community who hears of me and then dies without believing in what I have been sent with (the revelation) will surely be among the people of the Fire.”",
    "Muslim, Îmân, 240",
    "Faith · Affirming the Prophet",
  ),
  Hadith(
    "Ebû Hüreyre’den gelen rivayete göre,… Allah Resûlü (sav) şöyle buyurmuştur: “Kur’an’ı öğrenin, onu okuyun ve okutun. Kur’an’ı öğrenen, okuyan ve gereğini yapan kimse, her tarafa koku yayan misk dolu bir kaba benzer. Kur’an’ı öğrendiği hâlde (onu okumayan ve okutmayan) yatıp uyuyan kimse ise ağzı bağlı bir misk kabına benzer.”",
    "Tirmizî, Fedâilü’l-Kur’ân, 2",
    "İman · Kur’an-ı Kerim’i Öğrenmek ve Öğretmek",
    "It is narrated from Abu Hurairah that… the Messenger of Allah (peace be upon him) said: “Learn the Quran, recite it and teach it to others. The one who learns the Quran, recites it and acts upon it is like a vessel full of musk spreading its fragrance everywhere. And the one who learns the Quran but then lies down and sleeps (without reciting or teaching it) is like a vessel of musk whose mouth has been tied shut.”",
    "Tirmidhi, Fedâilü’l-Kur’ân, 2",
    "Faith · Learning and Teaching the Holy Quran",
  ),
  Hadith(
    "Ebû Hüreyre’den nakledildiğine göre, Allah Resûlü (sav) şöyle buyurmuştur: “Allah’a ve âhiret gününe iman eden kişi misafirine ikram etsin. Allah’a ve âhiret gününe iman eden kişi komşusunu rahatsız etmesin. Allah’a ve âhiret gününe iman eden kişi ya hayır söylesin ya da sussun.”",
    "Ebû Dâvûd, Edeb, 122, 123",
    "İman · İmanın Gereği",
    "It is narrated from Abu Hurairah that the Messenger of Allah (peace be upon him) said: “Whoever believes in Allah and the Last Day, let him honor his guest. Whoever believes in Allah and the Last Day, let him not trouble his neighbor. Whoever believes in Allah and the Last Day, let him speak good or remain silent.”",
    "Abu Dawud, Edeb, 122, 123",
    "Faith · What Faith Requires",
  ),
  Hadith(
    "Şeddâd b. Evs’ten nakledildiğine göre, Hz. Peygamber (sav) şöyle buyurmuştur: “Akıllı kişi kendisini hesaba çeken ve ölümden sonrası için çalışandır. Âciz kişi ise arzularına uyup bir de Allah’tan (bağışlanma) umandır.”",
    "Tirmizî, Sıfatü’l-kıyâme, 25",
    "İman · Muhasebe ve Ahirete Hazırlık",
    "It is narrated from Shaddad ibn Aws that the Prophet (peace be upon him) said: “The wise person is the one who holds himself to account and works for what comes after death. The helpless one is the one who follows his desires and then hopes (for forgiveness) from Allah.”",
    "Tirmidhi, Sıfatü’l-kıyâme, 25",
    "Faith · Self-Reckoning and Preparing for the Hereafter",
  ),
  Hadith(
    "Ebû Hüreyre’den (ra) nakledildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Mümin, yeşil ekine benzer. Rüzgârla eğilir (fakat yıkılmaz). Rüzgâr sakinleştiğinde yine doğrulur. İşte mümin de böyledir; o da bela ve musibetler sebebiyle eğilir (fakat yıkılmaz). Kâfir ise sert ve dimdik selvi ağacına benzer ki Allah onu dilediği zaman (bir defada) söküp devirir.”",
    "Buhârî, Tevhîd, 31",
    "İman · Mümin",
    "It is narrated from Abu Hurairah (may Allah be pleased with him) that the Messenger of Allah (peace be upon him) said: “The believer is like a green crop. The wind bends it (but does not break it), and when the wind calms down, it stands upright again. So it is with the believer: he too bends under trials and afflictions (but does not break). The disbeliever, however, is like a hard, rigid cypress tree, which Allah uproots and fells (all at once) whenever He wills.”",
    "Bukhari, Tevhîd, 31",
    "Faith · The Believer",
  ),
  Hadith(
    "İbn Ömer’in rivayet ettiğine göre, Hz. Peygamber (sav) şöyle buyurmuştur: “Münafık, iki sürü arasında gidip gelen şaşkın koyun gibidir. Bir o sürüye gider, bir bu sürüye!”",
    "Müslim, Sıfâtü’l-münâfıkîn, 17",
    "İman · Münafık",
    "Ibn Umar narrated that the Prophet (peace be upon him) said: “The hypocrite is like a bewildered sheep wavering between two flocks, going now to that flock, now to this one!”",
    "Muslim, Sıfâtü’l-münâfıkîn, 17",
    "Faith · The Hypocrite",
  ),
  Hadith(
    "Hz. Âişe’den rivayet edildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Güç yetirebileceğiniz amelleri yapmaya gayret ediniz. Allah usanmaz da siz usanırsınız. Allah katında amellerin en sevimlisi az da olsa devamlı olanıdır.”",
    "Ebû Dâvûd, Tatavvu’, 27",
    "İbadet · İbadetlerde Devamlılık",
    "It is narrated from Aisha that the Messenger of Allah (peace be upon him) said: “Strive to do the deeds that you are able to sustain. Allah does not grow weary, but you will grow weary. The most beloved of deeds to Allah are those done consistently, even if they are few.”",
    "Abu Dawud, Tatavvu’, 27",
    "Worship · Consistency in Worship",
  ),
  Hadith(
    "Ali b. Ebû Tâlib’den nakledildiğine göre, Hz. Peygamber vitir namazının sonunda şöyle dua ederdi: “Allah’ım! Gazabından rızana sığınırım, cezalandırmandan affına sığınırım. Senden (gelecek her türlü azaptan) Sana sığınırım. Seni lâyıkıyla övmeyi beceremem. Sen, kendini övdüğün gibisin.”",
    "Nesâî, Kıyâmü’l-leyl, 51",
    "İbadet · Vitir ve Dua",
    "It is narrated from Ali ibn Abi Talib that the Prophet (peace be upon him) used to supplicate at the end of the witr prayer: “O Allah! I seek refuge in Your pleasure from Your wrath, and in Your pardon from Your punishment. I seek refuge in You from You (from every kind of punishment that may come from You). I cannot praise You as You deserve. You are as You have praised Yourself.”",
    "Nasa'i, Kıyâmü’l-leyl, 51",
    "Worship · Witr and Supplication",
  ),
  Hadith(
    "Ebû Hüreyre’den rivayet edildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “İmam (kendisine uyanların namazlarına) kefil, müezzin ise (namaz vakitleri konusunda) kendisine güvenilen kimsedir. Allah’ım! İmamlara (kefil oldukları konuda) muvaffakiyet ver, müezzinleri de (olası taksirlerinden dolayı) bağışla!”",
    "Tirmizî, Salât, 39",
    "İbadet · İmamlık ve Müezzinlik",
    "It is narrated from Abu Hurairah that the Messenger of Allah (peace be upon him) said: “The imam is a guarantor (for the prayers of those who follow him), and the muezzin is one who is entrusted (with the prayer times). O Allah! Grant success to the imams (in what they guarantee), and forgive the muezzins (for their possible shortcomings)!”",
    "Tirmidhi, Salât, 39",
    "Worship · The Imam and the Muezzin",
  ),
  Hadith(
    "Ebû Hüreyre’den rivayet edildiğine göre, Hz. Peygamber (sav) şöyle buyurmuştur: “Güneşin doğduğu en hayırlı gün, Cuma günüdür. Âdem o gün yaratıldı, o gün cennete konuldu ve o gün cennetten çıkarıldı. Kıyamet de ancak Cuma günü kopacaktır.”",
    "Müslim, Cum’a, 18",
    "İbadet · Cuma Günü",
    "It is narrated from Abu Hurairah that the Prophet (peace be upon him) said: “The best day on which the sun has risen is Friday. On it Adam was created, on it he was placed in Paradise, and on it he was sent out of Paradise. And the Last Hour will take place on no day other than Friday.”",
    "Muslim, Cum’a, 18",
    "Worship · Friday",
  ),
  Hadith(
    "Ebû Hüreyre’den rivayet edildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “(Kıyamet günü) kulun ilk hesaba çekileceği şey namazıdır. Eğer bunu tam olarak yapmışsa (ne âlâ!) Ama (farz namazları tamam) değilse Yüce Allah, “Kulumun nafilelerine bakın.” buyurur. Eğer nafile namazı bulunursa, “Onunla farzları tamamlayın.” buyurur.”",
    "Nesâî, Salât, 9",
    "İbadet · Namaz ve İlk Hesap",
    "It is narrated from Abu Hurairah that the Messenger of Allah (peace be upon him) said: “The first thing for which a servant will be called to account (on the Day of Resurrection) is his prayer. If he has performed it completely, (all is well!) But if (his obligatory prayers) are not complete, Allah the Exalted will say: ‘Look at the voluntary prayers of My servant.’ If voluntary prayers are found, He will say: ‘Complete the obligatory ones with them.’”",
    "Nasa'i, Salât, 9",
    "Worship · Prayer and the First Reckoning",
  ),
  Hadith(
    "Ebû Hüreyre’den (ra) rivayet edildiğine göre, Hz. Peygamber (sav) şöyle buyurmuştur: “İnanarak ve sevabını Allah’tan umarak Ramazan orucunu tutan kimsenin geçmiş günahları bağışlanır. İnanarak ve sevabını Allah’tan umarak Kadir Gecesi’ni ihya eden kimsenin de geçmiş günahları bağışlanır.”",
    "Buhârî, Fadlü leyleti’l-kadr, 1",
    "İbadet · Ramazan Orucu ve Kadir Gecesi",
    "It is narrated from Abu Hurairah (may Allah be pleased with him) that the Prophet (peace be upon him) said: “Whoever fasts Ramadan out of faith and hoping for its reward from Allah, his past sins will be forgiven. And whoever spends the Night of Power in worship out of faith and hoping for its reward from Allah, his past sins will be forgiven.”",
    "Bukhari, Fadlü leyleti’l-kadr, 1",
    "Worship · Ramadan Fasting and the Night of Power",
  ),
  Hadith(
    "Ebû Zerr’in rivayet ettiğine göre, Resûlullah (sav) ona şöyle buyurmuştur: “Nerede olursan ol, Allah’a karşı sorumluluğunun bilincinde ol! Kötülüğün peşinden iyi bir şey yap ki onu yok etsin. İnsanlara da güzel ahlâka uygun biçimde davran!”",
    "Tirmizî, Birr, 55",
    "Güzel Ahlak · Takva ve İyilik",
    "Abu Dharr narrated that the Messenger of Allah (peace be upon him) said to him: “Be mindful of your responsibility toward Allah wherever you are! Follow a bad deed with a good one, so that it wipes it out. And treat people with good character!”",
    "Tirmidhi, Birr, 55",
    "Good Character · God-Consciousness and Goodness",
  ),
  Hadith(
    "Abdullah b. Ebû Bekir anlatıyor: Enes b. Mâlik’ten işittiğime göre, Resûlullah (sav) şöyle buyurmuştur: “Üç şey öleni (mezara kadar) takip eder; ikisi geri döner, biri kalır. Ailesi, malı ve ameli onu takip eder. Ailesi ve malı geri döner, ameli kalır.”",
    "Müslim, Zühd, 5",
    "Güzel Ahlak · Ahiret Azığı",
    "Abdullah ibn Abi Bakr narrates: I heard from Anas ibn Malik that the Messenger of Allah (peace be upon him) said: “Three things follow the deceased (to the grave); two return and one remains. His family, his wealth and his deeds follow him. His family and his wealth return, and his deeds remain.”",
    "Muslim, Zühd, 5",
    "Good Character · Provision for the Hereafter",
  ),
  Hadith(
    "Âmir’in en-Nu’mân b. Beşîr’den işittiğine göre, Allah Resûlü (sav) şöyle buyurmuştur: “…Bilin ki! Vücutta öyle bir et parçası vardır ki o, iyi (doğru ve düzgün) olursa bütün vücut iyi (doğru ve düzgün) olur; o bozulursa bütün vücut bozulur. Bilin ki! O, kalptir.”",
    "Buhârî, Îmân, 39",
    "Güzel Ahlak · Kalp",
    "Amir heard from al-Nu'man ibn Bashir that the Messenger of Allah (peace be upon him) said: “… Know that in the body there is a piece of flesh which, if it is sound (upright and well), the whole body is sound; and if it is corrupt, the whole body is corrupt. Know that it is the heart.”",
    "Bukhari, Îmân, 39",
    "Good Character · The Heart",
  ),
  Hadith(
    "Ebû Ümâme’den rivayet edildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Kim Allah için sever, Allah için nefret eder, Allah için verir, Allah için (kötülüklere) engel olursa, imanını kemale erdirmiş olur.”",
    "Ebû Dâvûd, Sünne, 15",
    "Güzel Ahlak · Yaptığını Allah (cc) İçin Yapmak",
    "It is narrated from Abu Umamah that the Messenger of Allah (peace be upon him) said: “Whoever loves for the sake of Allah, hates for the sake of Allah, gives for the sake of Allah, and withholds (from evil) for the sake of Allah has perfected his faith.”",
    "Abu Dawud, Sünne, 15",
    "Good Character · Doing Everything for Allah",
  ),
  Hadith(
    "İbn Ömer’den nakledildiğine göre, Resûlullah (sav) şöyle buyurdu: “İnsanlarla bir arada yaşayan ve onların eziyetlerine sabreden mümin, insanlarla bir arada yaşamayan ve onların eziyetlerine sabretmeyen müminden daha büyük ecre nail olur.”",
    "İİbn Mâce, Fiten 23; İbn Hanbel, II, 44",
    "Güzel Ahlak · Sabır",
    "It is narrated from Ibn Umar that the Messenger of Allah (peace be upon him) said: “The believer who mixes with people and bears patiently the harm they cause attains a greater reward than the believer who does not mix with people and does not bear patiently the harm they cause.”",
    "Ibn Majah, Fiten 23; Ahmad ibn Hanbal, II, 44",
    "Good Character · Patience",
  ),
  Hadith(
    "Abdurrahman b. Ebû Bekir anlatıyor: Suffe ashâbı fakir insanlardı. Hz. Peygamber (sav) şöyle buyurmuştu: “Kimin yanında iki kişilik yemek varsa üçüncü bir kişiyi, dört kişilik yiyeceği olan beşinci ya da altıncı bir kişiyi misafir etsin!”",
    "Buhârî, Mevâkîtü’s-salât, 41",
    "Güzel Ahlak · Misafire İkram Etmek",
    "Abd al-Rahman ibn Abi Bakr narrates: The People of the Suffa were poor. The Prophet (peace be upon him) had said: “Whoever has food for two, let him host a third person; and whoever has food for four, let him host a fifth or a sixth!”",
    "Bukhari, Mevâkîtü’s-salât, 41",
    "Good Character · Honoring Guests",
  ),
  Hadith(
    "Huzeyfe’nin işittiğine göre, Resûlullah (sav) şöyle buyurmuştur: “İnsan, ailesi, malı, nefsi, çocuğu ve komşusu ile sınanır; oruç, namaz, sadaka ve iyiliği emredip kötülükten sakındırma işte bu sınanma (esnasındaki kusurlarına) kefaret olur.”",
    "Müslim, Fiten, 26; Buhârî, Mevâkîtü’s-salât, 4",
    "Sosyal Hayat · İnsanın İmtihanı",
    "Hudhayfah heard the Messenger of Allah (peace be upon him) say: “A person is tested through his family, his wealth, his own self, his child and his neighbor; fasting, prayer, charity, and enjoining good and forbidding evil are an expiation for (his shortcomings during) this testing.”",
    "Muslim, Fiten, 26; Bukhari, Mevâkîtü’s-salât, 4",
    "Social Life · The Trials of a Person",
  ),
  Hadith(
    "Ebû Hüreyre’nin anlattığına göre, Hz. Peygamber (sav) şöyle buyurmuştur: “Kendi onayı alınmadıkça dul kadınla, kendisinden izin alınmadıkça da bakire kız ile nikâh yapılmaz.” Oradaki sahâbîler, “Yâ Resûlallah! Bakire bir kızın izni nasıl olur?” diye sordular. O (sav) da, “Sessiz kalmasıyla.” buyurdu.",
    "Buhârî, Nikâh, 42",
    "Sosyal Hayat · Evlilik",
    "Abu Hurairah narrated that the Prophet (peace be upon him) said: “A previously married woman may not be married without her consent, and a virgin may not be married without her permission.” The Companions present asked, “O Messenger of Allah! How is a virgin's permission given?” He (peace be upon him) said, “By her remaining silent.”",
    "Bukhari, Nikâh, 42",
    "Social Life · Marriage",
  ),
  Hadith(
    "Ebû Hüreyre’den nakledildiğine göre, Hz. Peygamber (sav) şöyle buyurmuştur: “Akrabalık ilişkilerinizi sürdürebilmeniz için neseplerinizi (sülâlenizi) tanıyın. Çünkü akrabalık bağlarının canlı tutulması ailede sevgiyi güçlendirir, malı artırır ve ömrü uzatır.”",
    "Tirmizî, Birr, 49; İbn Hanbel, II, 374",
    "Sosyal Hayat · Akrabalık Bağı",
    "It is narrated from Abu Hurairah that the Prophet (peace be upon him) said: “Know your lineages so that you may maintain your ties of kinship. For keeping the ties of kinship alive strengthens love within the family, increases wealth and lengthens life.”",
    "Tirmidhi, Birr, 49; Ahmad ibn Hanbal, II, 374",
    "Social Life · Ties of Kinship",
  ),
  Hadith(
    "Enes b. Mâlik’in rivayet ettiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Bir genç, ihtiyar bir kimseye yaşından dolayı hürmet ederse, Allah da ona yaşlılığında kendisine hürmet edecek birisini hazırlar.”",
    "Tirmizî, Birr, 75",
    "Sosyal Hayat · Yaşlıya Hürmet Etmek",
    "Anas ibn Malik narrated that the Messenger of Allah (peace be upon him) said: “If a young person honors an elderly person because of his age, Allah will appoint for him someone who will honor him in his old age.”",
    "Tirmidhi, Birr, 75",
    "Social Life · Respecting the Elderly",
  ),
  Hadith(
    "Ebû Hüreyre’den nakledildiğine göre, Hz. Peygamber (sav) şöyle buyurmuştur: “Müslümanlar(ın evleri) arasında en hayırlı ev, içinde kendisine iyi davranılan bir yetimin bulunduğu evdir. Müslümanlar arasında en kötü ev ise, içinde kendisine kötü davranılan bir yetimin bulunduğu evdir.”",
    "İİbn Mâce, Edeb, 6",
    "Sosyal Hayat · Yetimi Kollayıp Gözetmek",
    "It is narrated from Abu Hurairah that the Prophet (peace be upon him) said: “The best house among (the houses of) the Muslims is a house in which there is an orphan who is treated well. And the worst house among the Muslims is a house in which there is an orphan who is treated badly.”",
    "Ibn Majah, Edeb, 6",
    "Social Life · Caring for Orphans",
  ),
  Hadith(
    "Hz. Âişe’den nakledildiğine göre, Resûlullah (sav) bir hastayı ziyaret ettiğinde şöyle derdi: “Ey insanların Rabbi! Hastalığın sıkıntısını gider! Ona şifa ver, şifa veren sensin. Senin vereceğin şifadan başka şifa yoktur. Öyle bir şifa ver ki ardında hiç hastalık izi bırakmasın!”",
    "Müslim, Selâm, 47",
    "Sosyal Hayat · Hasta Ziyaretinde Dua",
    "It is narrated from Aisha that when the Messenger of Allah (peace be upon him) visited a sick person, he would say: “O Lord of mankind! Remove the hardship of the illness! Heal him, for You are the Healer. There is no healing but Your healing. Grant a healing that leaves no trace of illness behind!”",
    "Muslim, Selâm, 47",
    "Social Life · Supplication When Visiting the Sick",
  ),
  Hadith(
    "Ubâde b. Sâmit’den rivayet edildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Her kim, “Şehâdet ederim ki tek olan Allah’tan başka ilâh yoktur, (ortağı da yoktur); Muhammed O’nun kulu ve elçisidir; İsa da Allah’ın kulu ve Allah’ın kullarından bir kadının oğlu, Meryem’e ulaştırdığı (emriyle onda var ettiği) kelimesi ve Allah’tan (gelen) bir ruhtur. Cennet haktır, cehennem haktır.” derse Allah onu, cennetin sekiz kapısından hangisini dilerse oradan cennetine koyar.”",
    "Müslim, Îmân, 46",
    "İman · İman ve Mükâfatı",
    "It is narrated from Ubadah ibn al-Samit that the Messenger of Allah (peace be upon him) said: “Whoever says, ‘I bear witness that there is no god but Allah alone (who has no partner); that Muhammad is His servant and Messenger; that Jesus is the servant of Allah, the son of a woman from among the servants of Allah, His word which He conveyed to Mary (bringing him into being in her by His command), and a spirit from Allah; that Paradise is true and Hell is true,’ Allah will admit him into His Paradise through whichever of the eight gates of Paradise he wishes.”",
    "Muslim, Îmân, 46",
    "Faith · Faith and Its Reward",
  ),
  Hadith(
    "Hz. Ali, Resûlullah’tan (sav) şu sözleri duyduğunu haber vermiştir: “Hasta olan Müslüman kardeşini ziyarete giden kimse, onun yanında oturuncaya kadar (âdeta) cennet meyveleri içinde yürümüş olur. Oturduğu zaman onu rahmet kaplar. Eğer ziyareti sabahleyin olursa akşama kadar yetmiş bin melek onun için dua ve istiğfar eder. Ziyareti akşam olursa sabaha kadar yetmiş bin melek onun için dua ve istiğfar eder.”",
    "İİbn Mâce, Cenâiz, 2",
    "İman · Hasta Ziyareti ve Meleklerin Duası",
    "Ali reported that he heard the Messenger of Allah (peace be upon him) say: “Whoever goes to visit his sick Muslim brother walks (as it were) among the fruits of Paradise until he sits down beside him. When he sits down, mercy envelops him. If his visit is in the morning, seventy thousand angels pray for him and seek forgiveness for him until the evening. If his visit is in the evening, seventy thousand angels pray for him and seek forgiveness for him until the morning.”",
    "Ibn Majah, Cenâiz, 2",
    "Faith · Visiting the Sick and the Prayers of the Angels",
  ),
  Hadith(
    "Ebû Hüreyre’den rivayet edildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Hiçbir peygamber yoktur ki, insanların inanmaları için kendisine mucizeler verilmiş olmasın. Bana verilen ise Allah’ın vahyettiği vahiy (Kur’ân-ı Kerîm)dir. Bu sayede ben kıyamet günü ümmeti en çok olan peygamber olacağımı ümit ediyorum.”",
    "Buhârî, İ’tisâm, 1",
    "İman · Kur’an-ı Kerim ve Mucize",
    "It is narrated from Abu Hurairah that the Messenger of Allah (peace be upon him) said: “There is no prophet who was not given miracles so that people would believe. What I have been given is the revelation that Allah has revealed to me (the Holy Quran). Because of it, I hope to be the prophet with the most followers on the Day of Resurrection.”",
    "Bukhari, İ’tisâm, 1",
    "Faith · The Holy Quran and Miracles",
  ),
  Hadith(
    "Enes b. Mâlik’ten rivayet edildiğine göre, Resûlullah (sav), “Ne mutlu, beni görüp de iman edenlere!” sözünü bir kere söyledi. “Ne mutlu, beni görmeden iman edenlere!” ifadesini ise yedi defa tekrarladı.",
    "İbn Hanbel, III, 155",
    "İman · Peygambere İman",
    "It is narrated from Anas ibn Malik that the Messenger of Allah (peace be upon him) said once, “Blessed are those who saw me and believed!” And he repeated seven times, “Blessed are those who believed in me without seeing me!”",
    "Ahmad ibn Hanbal, III, 155",
    "Faith · Belief in the Prophet",
  ),
  Hadith(
    "Abdullah b. Amr b. el-Âs’ın işittiğine göre, Allah Resûlü (sav) şöyle buyurmuştur: “…Muhammed’in canı elinde olan Allah’a yemin olsun ki mümin bal arısına benzer; güzel şeyler yer, güzel şeyler üretir, (güzel yerlere) konar, (konduğu yeri de) kırmaz ve bozmaz.”",
    "İbn Hanbel, II, 199; Hâkim, Müstedrek , I, 110 (1/76)",
    "İman · Mümin",
    "Abdullah ibn Amr ibn al-As heard the Messenger of Allah (peace be upon him) say: “… By Allah, in whose hand is the soul of Muhammad, the believer is like the honeybee: it eats what is good, produces what is good, alights (on good places), and does not break or spoil (the place where it alights).”",
    "Ahmad ibn Hanbal, II, 199; Hâkim, Müstedrek , I, 110 (1/76)",
    "Faith · The Believer",
  ),
  Hadith(
    "Abdullah b. Amr’ın rivayet ettiğine göre, Hz. Peygamber (sav) şöyle buyurmuştur: “Şu dört özellik kimde bulunursa o, tam bir münafık olur. Kimde bu niteliklerden biri bulunursa onu terk edinceye kadar kendisinde münafıklıktan bir özellik vardır: Kendisine bir şey emanet edildiğinde hıyanet eder. Konuştuğunda yalan söyler. Söz verdiğinde cayar. Husumet sırasında haktan sapar.”",
    "Buhârî, Îmân, 24",
    "İman · Münafık",
    "It is narrated from Abdullah ibn Amr that the Prophet (peace be upon him) said: “Whoever has these four traits is a complete hypocrite, and whoever has one of them has a trait of hypocrisy until he abandons it: when he is entrusted with something, he betrays the trust; when he speaks, he lies; when he makes a promise, he breaks it; and when he quarrels, he deviates from the truth.”",
    "Bukhari, Îmân, 24",
    "Faith · The Hypocrite",
  ),
  Hadith(
    "İbn Abbâs’tan (ra) nakledildiğine göre, Hz. Peygamber (sav) Hasan ile Hüseyin için dua ederek şu sözlerle Allah’a sığınırdı: “Her tür şeytandan, haşereden, kem nazardan Allah’ın tam kelimelerine —sonsuz iradesine ve hükmüne— sığınırım.” Sonra da, “Atanız İbrâhim de bu duayı oğulları İsmâil ile İshak için yapardı.” derdi.",
    "Buhârî, Enbiyâ, 10",
    "İman · Allah’a (cc) Sığınmak",
    "It is narrated from Ibn Abbas (may Allah be pleased with him) that the Prophet (peace be upon him), praying for Hasan and Husayn, used to seek refuge in Allah for them with these words: “I seek refuge in the perfect words of Allah (His infinite will and decree) from every devil, from every harmful creature, and from every evil eye.” Then he would say, “Your forefather Abraham used to make this supplication for his sons Ishmael and Isaac.”",
    "Bukhari, Enbiyâ, 10",
    "Faith · Seeking Refuge in Allah",
  ),
  Hadith(
    "Hz. Âişe’den rivayet edildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Üç kişiden sorumluluk kaldırılmıştır: Uyuyandan uyanıncaya kadar, akıl hastalığına duçar olandan aklı başına gelinceye kadar ve çocuktan bulûğ (ergenlik) çağına gelinceye kadar.”",
    "Ebû Dâvûd, Hudûd, 17",
    "İbadet · Mükellefiyet",
    "It is narrated from Aisha that the Messenger of Allah (peace be upon him) said: “Responsibility is lifted from three people: from the one who is asleep until he wakes up, from the one afflicted with mental illness until he regains his sanity, and from the child until he reaches puberty.”",
    "Abu Dawud, Hudûd, 17",
    "Worship · Religious Accountability",
  ),
  Hadith(
    "Ebû Hüreyre’nin rivayet ettiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Yüce Allah buyuruyor ki: Kulum beni nasıl düşünüyorsa ben öyleyim. O, beni anarken ben onunla beraberim. O, beni kendi başına anarsa, ben de onu kendim anarım. O, beni bir topluluk içinde anarsa, ben onu daha hayırlı bir topluluk içinde anarım…”",
    "Müslim, Zikir, 2; Buhârî, Tevhîd, 15",
    "İbadet · Allah’ı Anmak",
    "Abu Hurairah narrated that the Messenger of Allah (peace be upon him) said: “Allah the Exalted says: I am as My servant thinks of Me. I am with him when he remembers Me. If he remembers Me in himself, I remember him in Myself. If he remembers Me in a gathering, I remember him in a gathering better than it…”",
    "Muslim, Zikir, 2; Bukhari, Tevhîd, 15",
    "Worship · Remembrance of Allah",
  ),
  Hadith(
    "Ebû Hüreyre’nin işittiğine göre, Resûlullah (sav) bir defasında şöyle demiştir: “Birinizin kapısının önünden bir nehir geçse ve onda her gün beş defa yıkansa, bu o kimsenin kirinden bir şey bırakır mı, ne dersiniz?” Sahâbîler, “Onun kirinden hiçbir şey bırakmaz.” demişler, bunun üzerine Resûlullah, “İşte beş vakit namaz da böyledir! Allah onlarla günahları yok eder.” buyurmuştur.",
    "Buhârî, Mevâkîtü’s-salât, 6",
    "İbadet · Namaz ve Arınma",
    "Abu Hurairah heard the Messenger of Allah (peace be upon him) say on one occasion: “What do you think: if a river passed by the door of one of you and he bathed in it five times every day, would any of his dirt remain?” The Companions said, “None of his dirt would remain.” Thereupon the Messenger of Allah said, “That is how the five daily prayers are! Through them Allah wipes away sins.”",
    "Bukhari, Mevâkîtü’s-salât, 6",
    "Worship · Prayer and Purification",
  ),
  Hadith(
    "Ebû Hüreyre’den nakledildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Müminin mümin üzerinde altı hakkı vardır: Hastalandığında onu ziyaret eder, öldüğünde cenazesinde bulunur, kendisini davet ettiğinde davetine icabet eder, onunla karşılaştığında selâm verir, aksırdığında ona hayır duada bulunur, yanında ve gıyabında onun için samimi davranır.”",
    "Tirmizî, Edeb, 1; Nesâî, Cenâiz, 52",
    "İbadet · Müminin Mümin Üzerindeki Hakkı",
    "It is narrated from Abu Hurairah that the Messenger of Allah (peace be upon him) said: “A believer has six rights over another believer: he visits him when he is ill, attends his funeral when he dies, accepts his invitation when he invites him, greets him with salam when he meets him, prays for him when he sneezes, and is sincere toward him whether he is present or absent.”",
    "Tirmidhi, Edeb, 1; Nasa'i, Cenâiz, 52",
    "Worship · The Rights of a Believer over a Believer",
  ),
  Hadith(
    "Ebû Hüreyre’den rivayet edildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Mübarek Ramazan ayı size geldi. Yüce Allah bu ayda size oruç tutmayı farz kıldı. Bu ayda sema (cennet) kapıları açılır, cehennem kapıları ise kapanır ve şeytanların azgınları bağlanır.”",
    "Nesâî, Sıyâm, 5",
    "İbadet · Ramazan Ayı",
    "It is narrated from Abu Hurairah that the Messenger of Allah (peace be upon him) said: “The blessed month of Ramadan has come to you. Allah the Exalted has made fasting in this month obligatory upon you. In this month the gates of heaven (Paradise) are opened, the gates of Hell are closed, and the most rebellious of the devils are chained.”",
    "Nasa'i, Sıyâm, 5",
    "Worship · The Month of Ramadan",
  ),
  Hadith(
    "Ebû Hüreyre’nin rivayet ettiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Büyük günahlardan kaçınıldığı takdirde, beş vakit namaz ile Cuma, bir sonraki cumaya kadar ve Ramazan diğer Ramazan’a kadar, aralarında işlenen günahların bağışlanmasına vesiledir.”",
    "Müslim, Tahâret, 16",
    "İbadet · Cuma ve Ramazan",
    "Abu Hurairah narrated that the Messenger of Allah (peace be upon him) said: “As long as major sins are avoided, the five daily prayers, Friday until the next Friday, and Ramadan until the next Ramadan are a means of forgiveness for the sins committed between them.”",
    "Muslim, Tahâret, 16",
    "Worship · Friday and Ramadan",
  ),
  Hadith(
    "Ömer b. Hattâb’ın naklettiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Ameller niyete göredir. Herkes sadece niyetinin karşılığını alır. Kim Allah ve Resûlü için hicret ederse, hicreti Allah ve Resûlü’nedir. Kim de erişeceği bir dünyalık veya evleneceği bir kadından dolayı hicret ederse, onun hicreti de hicretine sebep olan şeyedir.”",
    "Müslim, İmâre, 155; Buhârî, Bedü’l-vahy, 1",
    "Güzel Ahlak · Niyet ve Önemi",
    "Umar ibn al-Khattab narrated that the Messenger of Allah (peace be upon him) said: “Deeds are judged by intentions. Everyone will receive only what he intended. Whoever emigrates for Allah and His Messenger, his emigration is for Allah and His Messenger. And whoever emigrates for some worldly gain he seeks or a woman he wishes to marry, his emigration is for that for which he emigrated.”",
    "Muslim, İmâre, 155; Bukhari, Bedü’l-vahy, 1",
    "Good Character · Intention and Its Importance",
  ),
  Hadith(
    "Abdullah b. Ömer’in (ra) işittiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Hepiniz sorumlusunuz ve hepiniz yönettiklerinizden mesulsünüz. Devlet başkanı bir sorumludur ve yönettiklerinden mesuldür. Evin beyi bir sorumludur ve yönettiklerinden mesuldür. Evin hanımı da bir sorumludur ve yönettiklerinden mesuldür. Hizmetçi de efendisinin malı üzerinde bir sorumludur ve yönettiklerinden mesuldür.”",
    "Buhârî, İstikrâz, 20",
    "Güzel Ahlak · Sorumluluk",
    "Abdullah ibn Umar (may Allah be pleased with him) heard the Messenger of Allah (peace be upon him) say: “Each of you is a guardian, and each of you is responsible for those in your care. The head of state is a guardian and is responsible for those in his care. The man of the house is a guardian and is responsible for those in his care. The woman of the house is also a guardian and is responsible for those in her care. The servant is also a guardian over his master’s property and is responsible for what is in his care.”",
    "Bukhari, İstikrâz, 20",
    "Good Character · Responsibility",
  ),
  Hadith(
    "Enes b. Mâlik’ten rivayet edildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Kim hiçbir ortağı olmayan, tek olan Allah’a ihlâsla ibadet ederek, namazı dosdoğru kılarak, zekâtı vererek dünyadan ayrılırsa, Allah kendisinden razı olduğu hâlde ölmüş olur.”",
    "İİbn Mâce, Sünnet, 9",
    "Güzel Ahlak · İhlas",
    "It is narrated from Anas ibn Malik that the Messenger of Allah (peace be upon him) said: “Whoever leaves this world having worshipped Allah, the One who has no partner, with sincerity, having established the prayer and given the zakat, dies while Allah is pleased with him.”",
    "Ibn Majah, Sünnet, 9",
    "Good Character · Sincerity",
  ),
  Hadith(
    "Ubâde b. Sâmit’ten nakledildiğine göre, Hz. Peygamber (sav) şöyle buyurmuştur: “Bana kendi adınıza altı şeyin güvencesini verin, ben de size cennetin güvencesini vereyim: Konuştuğunuzda doğru söyleyin, söz verdiğinizde sözünüzü tutun, size (bir şey) emanet edildiğinde ona riayet edin, iffetinizi koruyun, gözlerinizi (bakılması yasak olandan) sakının ve ellerinizi (haramdan) çekin. ”",
    "İbn Hanbel, V, 323",
    "Güzel Ahlak · Sorumluluk",
    "It is narrated from Ubadah ibn al-Samit that the Prophet (peace be upon him) said: “Guarantee me six things on your part, and I will guarantee you Paradise: be truthful when you speak, keep your promise when you make one, honor a trust when (something) is entrusted to you, guard your chastity, lower your gaze (from what is forbidden to look at), and restrain your hands (from what is unlawful).”",
    "Ahmad ibn Hanbal, V, 323",
    "Good Character · Responsibility",
  ),
  Hadith(
    "Ömer b. Hattâb’ın naklettiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Eğer siz gereği gibi Allah’a tevekkül etmiş olsaydınız, tıpkı sabahleyin kursakları boş olarak çıkıp (akşam) doymuş bir şekilde dönen kuşların rızıklandırıldığı gibi sizler de rızıklandırılırdınız.”",
    "Tirmizî, Zühd, 33; İİbn Mâce, Zühd, 14",
    "Güzel Ahlak · Tevekkül",
    "Umar ibn al-Khattab narrated that the Messenger of Allah (peace be upon him) said: “If you were to rely on Allah as He truly deserves to be relied upon, you would be provided for just as the birds are provided for: they go out in the morning with empty stomachs and return (in the evening) full.”",
    "Tirmidhi, Zühd, 33; Ibn Majah, Zühd, 14",
    "Good Character · Trust in Allah",
  ),
  Hadith(
    "Enes b. Mâlik anlatıyor: Resûlullah (sav) bana dedi ki: “Evlâdım! Eğer kalbinde hiç kimseye karşı hile olmadan sabaha ve akşama erişmeyi başarabilirsen bunu yap. İşte bu benim sünnetimdir. Kim benim sünnetimi yaşatırsa beni sevmiş olur, kim de beni severse cennette benimle birlikte olur.”",
    "Tirmizî, İlim, 16",
    "Güzel Ahlak · Hileden Sakınmak",
    "Anas ibn Malik relates that the Messenger of Allah (peace be upon him) said to him: “My son! If you are able to reach the morning and the evening without holding deceit against anyone in your heart, then do so. This is my Sunnah. Whoever keeps my Sunnah alive has loved me, and whoever loves me will be with me in Paradise.”",
    "Tirmidhi, İlim, 16",
    "Good Character · Avoiding Deceit",
  ),
  Hadith(
    "Abdullah b. Amr’dan nakledildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Merhametliler, Rahmân’ın merhamet ettiği kimselerdir. Siz yeryüzündekilere merhamet edin ki göktekiler de size merhamet etsin! “Rahim” Rahmân’(dan) bir bağdır. Kim onunla irtibatını sürdürürse Allah da onunla irtibatını sürdürür; kim de onu koparırsa Allah da o kimseyle ilişkisini koparır.”",
    "Tirmizî, Birr, 16",
    "Sosyal Hayat · Merhamet",
    "It is narrated from Abdullah ibn Amr that the Messenger of Allah (peace be upon him) said: “The merciful are those to whom the Most Merciful (al-Rahman) shows mercy. Show mercy to those on earth, so that those in the heavens will show mercy to you! The ‘rahim’ (the bond of kinship) is a bond (derived) from al-Rahman. Whoever maintains it, Allah maintains His bond with him; and whoever severs it, Allah severs His bond with that person.”",
    "Tirmidhi, Birr, 16",
    "Social Life · Mercy",
  ),
  Hadith(
    "Ebû Hüreyre’den nakledildiğine göre, Hz. Peygamber (sav) şöyle buyurmuştur: “Bir Müslüman öldüğünde, en yakın komşularından üç hane halkı kendisinin iyi bir insan olduğuna şahitlik ederlerse, Yüce Allah, “Bildikleri kadarıyla şahitlikte bulunan kullarımın şahitliğini kabul ettim ve kendi bildiklerimi de bağışladım.” buyurur.”",
    "İbn Hanbel, II, 409",
    "Sosyal Hayat · İyi İnsan Olmak",
    "It is narrated from Abu Hurairah that the Prophet (peace be upon him) said: “When a Muslim dies and the members of three households among his closest neighbors testify that he was a good person, Allah the Exalted says, ‘I have accepted the testimony of My servants who testified according to what they knew, and I have forgiven what I know (of him).’”",
    "Ahmad ibn Hanbal, II, 409",
    "Social Life · Being a Good Person",
  ),
  Hadith(
    "Ebû Saîd el-Hudrî’nin işittiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Sizden herhangi biriniz bir kötülük görürse onu hemen eliyle değiştirsin. Buna gücü yetmiyorsa diliyle değiştirsin, ona da gücü yetmiyorsa kalbiyle (o kötülüğe) tavır koysun, (onu hoş görmesin). Ve bu da imanın asgarî gereğidir.”",
    "Müslim, Îmân, 78",
    "Sosyal Hayat · Emr-i Bi’l-Ma’ruf ve Nehyi Ani’l-Münker",
    "Abu Said al-Khudri heard the Messenger of Allah (peace be upon him) say: “Whoever among you sees an evil, let him change it at once with his hand. If he is unable to do so, then with his tongue; and if he is unable to do that, then let him take a stand against it with his heart (and not approve of it). And that is the least that faith requires.”",
    "Muslim, Îmân, 78",
    "Social Life · Enjoining Good and Forbidding Evil",
  ),
  Hadith(
    "Zeyd b. Hâlid el-Cühenî’den nakledildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Her kim Allah yolunda savaşacak bir askeri (savaş için) donatırsa kendisi de savaşmış gibi olur. Kim de Allah yolunda savaşa çıkan gazinin arkasından ailesine iyi bir şekilde göz kulak olursa o da savaşmış gibi olur.”",
    "Müslim, İmâre, 135; Buhârî, Cihâd, 38",
    "Sosyal Hayat · Allah Yolunda Savaşanı Desteklemek",
    "It is narrated from Zayd ibn Khalid al-Juhani that the Messenger of Allah (peace be upon him) said: “Whoever equips a soldier (for battle) to fight in the way of Allah is as though he himself has fought. And whoever looks after the family of a warrior who has gone out to fight in the way of Allah, caring for them well in his absence, is also as though he has fought.”",
    "Muslim, İmâre, 135; Bukhari, Cihâd, 38",
    "Social Life · Supporting Those Who Fight in the Way of Allah",
  ),
  Hadith(
    "Humeyd diyor ki, “Enes b. Mâlik’ten (ra) işittiğime göre, Hz. Peygamber (sav) şöyle buyurmuştur: “Ölüp de Allah katında hayırlı bir mertebeye erişen kullar içinde, şehitten başka hiç kimse -kendisine içindekilerle birlikte dünya verilecek olsa bile- yeniden dünyaya gelmek istemez. Şehit, şehitliğin ne kadar üstün bir mertebe olduğunu gördüğü için, dünyaya dönüp bir kez daha şehit olmayı arzular.”",
    "Buhârî, Cihâd, 6",
    "Sosyal Hayat · Şehitlik",
    "Humayd says: “I heard from Anas ibn Malik (may Allah be pleased with him) that the Prophet (peace be upon him) said: ‘Of the servants who die and attain a good rank with Allah, none would wish to return to the world, even if he were given the world and everything in it, except the martyr. Because the martyr sees how exalted the rank of martyrdom is, he longs to return to the world and be martyred once more.’”",
    "Bukhari, Cihâd, 6",
    "Social Life · Martyrdom",
  ),
  Hadith(
    "Ümmü Seleme’nin naklettiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Birinizin başına bir musibet/acı bir şey geldiği zaman, “Biz Allah’a aidiz ve biz O’na döneceğiz. Allah’ım! Başıma gelen musibetin/acının mükâfatını senden bekliyorum, bundan dolayı bana ecir ihsan et, benim için onu daha hayırlısıyla değiştir.” desin.”",
    "Ebû Dâvûd, Cenâiz, 17-18; Müslim, Cenâiz, 3",
    "Sosyal Hayat · Musibet ve Dua",
    "Umm Salamah narrated that the Messenger of Allah (peace be upon him) said: “When an affliction or something painful befalls any of you, let him say: ‘We belong to Allah and to Him we shall return. O Allah! I seek from You the reward for the affliction that has befallen me; so reward me for it and replace it for me with something better.’”",
    "Abu Dawud, Cenâiz, 17-18; Muslim, Cenâiz, 3",
    "Social Life · Affliction and Supplication",
  ),
  Hadith(
    "(Resûlullah’ın torunu) Hasan b. Ali (ra) şöyle demiştir: “Allah Resûlü (sav) vitirde okumam için bana şu duayı öğretti: “Allah’ım, hidayete erdirdiklerinle beraber beni de hidayete erdir. Sıhhat ve afiyet verdiklerinle beraber bana da afiyet ver. Himaye ettiğin kimseler gibi beni de himaye et. Bana verdiğin nimetleri bereketlendir. Verdiğin hükmün şerrinden beni koru. Hükmü sen verirsin, senin üstüne hüküm verecek kimse yoktur. Senin dost olduğun kimse asla zelil olmaz. Eksiklikler sana yakışmaz. Ey Rabbimiz! Yücesin ve kutlusun.”",
    "Tirmizî, Vitr, 10",
    "İman · Allah’a İman",
    "Hasan ibn Ali (may Allah be pleased with him), the grandson of the Messenger of Allah, said: “The Messenger of Allah (peace be upon him) taught me this supplication to recite in the Witr prayer: ‘O Allah, guide me among those whom You have guided. Grant me well-being among those to whom You have granted health and well-being. Take me into Your protection among those whom You protect. Bless for me what You have given me. Protect me from the evil of what You have decreed. For You decree, and none can decree over You. The one whom You befriend is never humbled. No imperfection befits You. Our Lord! You are Exalted and Blessed.’”",
    "Tirmidhi, Vitr, 10",
    "Faith · Faith in Allah",
  ),
  Hadith(
    "Muâz b. Cebel anlatıyor: Allah Resûlü (sav) ile Tebük Seferi’nden dönüyorduk. Onun yalnız olduğunu görünce, “Yâ Resûlallah! Bana cennete girmemi sağlayacak bir davranış söyler misin?” dedim. Bunun üzerine Hz. Peygamber (sav) şöyle buyurdu: “Aferin sana! Sen önemli bir konu hakkında soru sordun. Fakat bu, Allah’ın kendisi için kolaylaştırdığı kişiye kolay gelir. Farz namazı kılarsın, farz olan zekâtı verirsin ve O’na hiçbir şeyi ortak koşmayarak Allah’a kavuşursun…”",
    "İbn Hanbel, V, 237",
    "İman · Cennete Girmeye Vesile Davranışlar",
    "Muadh ibn Jabal relates: We were returning with the Messenger of Allah (peace be upon him) from the expedition of Tabuk. When I saw that he was alone, I said, “O Messenger of Allah! Will you tell me of a deed that will lead me into Paradise?” Thereupon the Prophet (peace be upon him) said: “Well done! You have asked about a weighty matter. Yet it is easy for the one for whom Allah makes it easy. You perform the obligatory prayer, you give the obligatory zakat, and you meet Allah without associating anything with Him…”",
    "Ahmad ibn Hanbal, V, 237",
    "Faith · Deeds That Lead to Paradise",
  ),
  Hadith(
    "İbn Abbâs’tan nakledildiğine göre, Hz. Peygamber (sav) şöyle buyurmuştur: “Nazar (göz değmesi) gerçektir. Eğer kaderin önüne geçecek bir şey olsaydı nazar onun önüne geçerdi…”",
    "Müslim, Selâm, 42",
    "İman · Göz Değmesi (Nazar)",
    "It is narrated from Ibn Abbas that the Prophet (peace be upon him) said: “The evil eye is real. If anything could outstrip destiny, it would be the evil eye…”",
    "Muslim, Selâm, 42",
    "Faith · The Evil Eye",
  ),
  Hadith(
    "Abdullah b. Abbâs, bir gün aynı binit üzerinde Allah Resûlü’nün (sav) arkasındayken onun kendisine şöyle dediğini anlattı: “Delikanlı! Sana bazı şeyler öğreteceğim. Allah’ı gözet ki Allah da seni gözetsin. Allah’ı gözet ki Allah’ı (daima) yanında bulasın. Bir şey istediğinde Allah’tan iste! Yardıma muhtaç olduğunda Allah’tan yardım dile! Şunu bil ki bütün insanlar sana fayda vermek için toplansa Allah’ın takdiri dışında sana fayda veremezler. Ve yine bütün insanlar sana zarar vermek için toplansa Allah’ın takdiri dışında sana hiçbir şeyde zarar veremezler. Bu konuda kalemler kaldırılmış (karar verilmiş), sayfalar kurumuştur (hüküm kesinleşmiştir).”",
    "İbn Hanbel, I, 293; Tirmizî, Sıfatü’l-kıyâme, 59",
    "İman · Allah’a İtaat ve Teslimiyet",
    "Abdullah ibn Abbas related that one day, while he was riding behind the Messenger of Allah (peace be upon him) on the same mount, he said to him: “Young man! I will teach you some words. Be mindful of Allah, and Allah will protect you. Be mindful of Allah, and you will (always) find Him beside you. When you ask, ask of Allah! When you need help, seek help from Allah! Know that if all people gathered together to benefit you, they could not benefit you except as Allah has decreed. And if all people gathered together to harm you, they could not harm you in anything except as Allah has decreed. On this matter the pens have been lifted (the decision has been made) and the pages have dried (the judgment is final).”",
    "Ahmad ibn Hanbal, I, 293; Tirmidhi, Sıfatü’l-kıyâme, 59",
    "Faith · Obedience and Submission to Allah",
  ),
  Hadith(
    "İbn Ömer anlatıyor: “Bir gün Allah Resûlü (sav) (benim de aralarında bulunduğum bir topluluğa), “Bana bir ağaç söyleyin ki o ağaç Müslüman’a benzer, Rabbinin izniyle her zaman meyve verir ve yaprakları da dökülmez.” buyurdu. İçimden, “Bu, hurma ağacıdır.” demek geldi. Fakat orada Ebû Bekir ve Ömer varken konuşmayı uygun bulmadım. Ancak onlar da konuşmayınca Allah Resûlü, “Bu, hurma ağacıdır.” buyurdu.”",
    "Buhârî, Edeb, 89",
    "İman · Mümin",
    "Ibn Umar relates: “One day the Messenger of Allah (peace be upon him) said (to a group among whom I was present), ‘Tell me of a tree that resembles a Muslim: by its Lord’s permission it gives fruit at all times, and its leaves do not fall.’ It occurred to me to say, ‘It is the date palm.’ But since Abu Bakr and Umar were there, I did not think it proper to speak. When they did not speak either, the Messenger of Allah said, ‘It is the date palm.’”",
    "Bukhari, Edeb, 89",
    "Faith · The Believer",
  ),
  Hadith(
    "Ebû Hüreyre’nin (ra) rivayet ettiğine göre, Hz. Peygamber (sav) şöyle buyurmuştur: “Kıyamet günü Allah katında insanların en kötülerinin şunlara bir yüzle, bunlara diğer bir yüzle gelen ikiyüzlüler olduğunu görürsün!”",
    "Buhârî, Edeb, 52",
    "İman · İkiyüzlülük",
    "Abu Hurairah (may Allah be pleased with him) narrated that the Prophet (peace be upon him) said: “On the Day of Resurrection you will find that the worst of people in the sight of Allah are the two-faced, who come to some people with one face and to others with another face!”",
    "Bukhari, Edeb, 52",
    "Faith · Two-Facedness",
  ),
  Hadith(
    "Ebû Hüreyre’nin naklettiğine göre, Allah Resûlü (sav) şöyle buyurmuştur: “Sizden aşağıda olanlara bakın; yukarıda olanlara bakmayın. Bu, Allah’ın (size verdiği) nimetleri küçümsememeniz bakımından daha uygun olur.”",
    "Müslim, Zühd, 9",
    "İman · Rızık ve Kanaat",
    "Abu Hurairah narrated that the Messenger of Allah (peace be upon him) said: “Look at those who are below you; do not look at those who are above you. This is more fitting, so that you do not belittle the blessings of Allah (upon you).”",
    "Muslim, Zühd, 9",
    "Faith · Sustenance and Contentment",
  ),
  Hadith(
    "Ebû Hüreyre’den (ra) nakledildiğine göre, Hz. Peygamber (sav) şöyle buyurmuştur: “Vücuttaki bütün eklemler için her gün sadaka vermek gerekir. Bineğine binmek isteyen kişiye yardım etmek veya eşyasını bineğine yüklemek sadakadır. Güzel söz ve namaza giderken atılan her adım sadakadır. Yol göstermek sadakadır.”",
    "Buhârî, Cihâd, 72",
    "İbadet · Sadaka",
    "It is narrated from Abu Hurairah (may Allah be pleased with him) that the Prophet (peace be upon him) said: “Charity is due every day for every joint of the body. Helping a person who wants to mount his riding animal, or loading his belongings onto it, is charity. A good word, and every step taken on the way to prayer, is charity. Showing someone the way is charity.”",
    "Bukhari, Cihâd, 72",
    "Worship · Charity",
  ),
  Hadith(
    "Ebû Hüreyre’nin rivayet ettiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Yüce Allah şöyle buyurur: “Kim benim bir velî kuluma (dostuma) düşmanlık ederse, ben de ona harp ilân ederim. Kulum, kendisine farz kıldığım şeylerden daha sevimli bir şeyle bana yaklaşamaz. Kulum nafile ibadetlerle de bana yaklaşmaya devam eder, ta ki ben onu severim. (Sevince de) artık onun işiten kulağı, gören gözü, tutan eli, yürüyen ayağı olurum. Benden isterse muhakkak ona (istediğini) veririm. Bana sığınırsa muhakkak onu korur ve kollarım…”",
    "Buhârî, Rikâk, 38",
    "İbadet · Allah’a Dost Olmak",
    "Abu Hurairah narrated that the Messenger of Allah (peace be upon him) said: “Allah the Exalted says: ‘Whoever shows enmity to a wali (friend) of Mine, I declare war on him. My servant does not draw near to Me with anything more beloved to Me than what I have made obligatory upon him. And My servant continues to draw near to Me with voluntary acts of worship until I love him. (And when I love him,) I become his hearing with which he hears, his sight with which he sees, his hand with which he grasps, and his foot with which he walks. If he asks of Me, I will surely give him (what he asks). If he seeks refuge in Me, I will surely protect and guard him…’”",
    "Bukhari, Rikâk, 38",
    "Worship · Being a Friend of Allah",
  ),
  Hadith(
    "İbn Ömer’den rivayet edildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Sizden her kime dua kapısı açılmış ise ona rahmet kapıları açılmıştır. Allah’tan istenilen şeyler arasında O’na en sevimli geleni, afiyettir.” Resûlullah (sav) konuşmasına şöyle devam etmiştir: “Dua, başa gelen ve henüz gelmeyen belaya karşı fayda sağlar. Öyleyse ey Allah’ın kulları, duaya sarılın!”",
    "Tirmizî, Deavât, 101",
    "İbadet · Dua",
    "It is narrated from Ibn Umar that the Messenger of Allah (peace be upon him) said: “Whoever among you has had the door of supplication opened to him, the doors of mercy have been opened to him. Of all the things Allah is asked for, the most beloved to Him is well-being.” The Messenger of Allah (peace be upon him) continued: “Supplication benefits against calamity that has befallen and that which has not yet befallen. So, O servants of Allah, hold fast to supplication!”",
    "Tirmidhi, Deavât, 101",
    "Worship · Supplication",
  ),
  Hadith(
    "Ebû Hüreyre’den nakledildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Müslüman -veya mümin- bir kul/kişi abdest alır da yüzünü yıkarsa, gözleri ile baktığı her günah suyla -yahut suyun son damlasıyla- yüzünden çıkar gider. Ellerini yıkadığı zaman elleriyle işlediği her günah su ile -yahut suyun son damlası ile- beraber ellerinden çıkar gider. Ayaklarını yıkadığı zaman ayaklarının yürüyerek işlediği her günah su ile -yahut suyun son damlasıyla- birlikte çıkar gider. Sonunda o kul/kişi günahlarından arınmış olur.”",
    "Müslim, Tahâret, 32; Tirmizî, Tahâret, 1",
    "İbadet · Abdest ve Arınma",
    "It is narrated from Abu Hurairah that the Messenger of Allah (peace be upon him) said: “When a Muslim (or believing) servant performs ablution and washes his face, every sin he looked at with his eyes leaves his face with the water (or with the last drop of water). When he washes his hands, every sin his hands committed leaves his hands with the water (or with the last drop of water). When he washes his feet, every sin his feet walked toward leaves with the water (or with the last drop of water). In the end, that servant emerges purified of his sins.”",
    "Muslim, Tahâret, 32; Tirmidhi, Tahâret, 1",
    "Worship · Ablution and Purification",
  ),
  Hadith(
    "Ebû Hüreyre’den rivayet edildiğine göre, Hz. Peygamber (sav) şöyle buyurmuştur: “İmam ancak kendisine uyulmak için vardır. Öyleyse (namazda) ondan farklı davranmayın. O rükûa varınca siz de rükûa varın. “Semiallâhü limen hamideh.” dediği zaman “Rabbenâ leke’l-hamd.” deyin. Secdeye gittiği zaman siz de secdeye gidin. Oturarak namaz kıldığı vakit siz de hep birlikte oturarak kılın. Namazda safı düzgün tutun. Çünkü safı düzgün tutmak namazın güzelliğindendir.”",
    "Buhârî, Ezân, 74",
    "İbadet · İmam, Cemaat ve Saf Düzeni",
    "It is narrated from Abu Hurairah that the Prophet (peace be upon him) said: “The imam is there only to be followed, so do not act differently from him (in prayer). When he bows, you bow. When he says, ‘Sami’allahu liman hamidah,’ say, ‘Rabbana laka’l-hamd.’ When he prostrates, you prostrate. When he prays sitting, all of you pray sitting. Keep the rows straight in prayer, for keeping the rows straight is part of the beauty of prayer.”",
    "Bukhari, Ezân, 74",
    "Worship · The Imam, the Congregation and the Rows",
  ),
  Hadith(
    "Ebû Hüreyre’nin naklettiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Kim abdest alır ve abdesti güzelce almaya özen gösterir sonra cumaya gelir ve (hutbeye) kulak verip sessizce dinlerse o Cuma ile gelecek Cuma arasındaki günahları ve üç günlük (günahı) daha affolunur. Kim de (hutbeyi dinlemeyip yerdeki) çakıl taşlarıyla meşgul olursa boş bir şey yapmıştır.”",
    "Müslim, Cum’a, 27",
    "İbadet · Cuma ve Hutbe",
    "Abu Hurairah narrated that the Messenger of Allah (peace be upon him) said: “Whoever performs ablution and takes care to do it well, then comes to the Friday prayer and listens attentively and silently (to the sermon), his sins between that Friday and the next, and three days more, are forgiven. And whoever busies himself with the pebbles (on the ground instead of listening to the sermon) has engaged in idle play.”",
    "Muslim, Cum’a, 27",
    "Worship · Friday and the Sermon",
  ),
  Hadith(
    "Ebû Hüreyre’nin naklettiğine göre, Resûlullah (sav) şöyle buyurmuştur: “İzzet ve celâl sahibi Allah şöyle buyurdu: “Kulum iyi bir iş yapmaya niyet eder de yapmazsa ona bir iyilik bir kötülük yapmaya niyet eder de yapmazsa onu (bir günah olarak) yazmam. Fakat onu yaparsa ona bir kötülük (günahı) yazarım.”",
    "Müslim, Îmân, 204; Buhârî, Rikâk, 31",
    "Güzel Ahlak · İyilik ve Kötülüğün Karşılığı",
    "Abu Hurairah narrated that the Messenger of Allah (peace be upon him) said: “Allah, the Possessor of Might and Majesty, said: ‘When My servant intends to do a good deed but does not do it, (I record) one good deed for him; and when he intends to do an evil deed but does not do it, I do not record it (as a sin). But if he does it, I record one evil deed (sin) against him.’”",
    "Muslim, Îmân, 204; Bukhari, Rikâk, 31",
    "Good Character · The Recompense of Good and Evil Deeds",
  ),
  Hadith(
    "Ebû Hüreyre’nin işittiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Allah rahmeti yüz parçaya ayırdı, doksan dokuz parçasını yanında tuttu, bir parçasını ise yeryüzüne indirdi. İşte bu bir parça (rahmet) sayesinde bütün mahlûklar birbirlerine merhametli davranırlar. Hatta kısrak (yavrusunu emzirirken) basıp da ona zarar verme korkusuyla ayağını (bu rahmetin eseriyle) kaldırır.”",
    "Buhârî, Edeb,19",
    "Güzel Ahlak · Merhamet",
    "Abu Hurairah heard the Messenger of Allah (peace be upon him) say: “Allah divided mercy into one hundred parts. He kept ninety-nine parts with Himself and sent down one part to the earth. It is through this one part (of mercy) that all creatures show mercy to one another, so much so that a mare (as a result of this mercy) lifts her hoof away from her foal (while nursing it), fearing she might step on it and harm it.”",
    "Bukhari, Edeb,19",
    "Good Character · Mercy",
  ),
  Hadith(
    "Huzeyfe (b. Yemân) tarafından nakledildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “İnsanlar iyilik yaparlarsa biz de iyilik yaparız, zulmederlerse biz de zulmederiz.” diyen zayıf karakterli kimseler olmayın. Bilakis iyilik yaptıklarında insanlara iyilikle karşılık vermeyi, kötülük yaptıklarında ise onlara zulmetmemeyi alışkanlık hâline getirin.”",
    "Tirmizî, Birr, 63",
    "Güzel Ahlak · İyilik ve Sağlam Karakter",
    "It is narrated by Hudhayfah (ibn al-Yaman) that the Messenger of Allah (peace be upon him) said: “Do not be people of weak character who say, ‘If people do good, we will do good; and if they do wrong, we will do wrong.’ Rather, make it your habit to repay people with goodness when they do good, and not to wrong them when they do evil.”",
    "Tirmidhi, Birr, 63",
    "Good Character · Kindness and Strong Character",
  ),
  Hadith(
    "Enes b. Mâlik’ten rivayet edildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Öyle insanlar vardır ki (âdeta) hayrın anahtarları, şerrin sürgüleri gibidir. Kimisi de şerrin anahtarları ve hayrın sürgüleri gibidir. Ne mutlu! Yüce Allah’ın, hayrın anahtarlarını ellerine verdiği o kimselere! Ve yazıklar olsun Yüce Allah’ın şerrin anahtarlarını ellerine verdiği o kimselere!”",
    "İİbn Mâce, Sünnet, 19",
    "Güzel Ahlak · Hayra Anahtar, Şerre Kilit Olmak",
    "It is narrated from Anas ibn Malik that the Messenger of Allah (peace be upon him) said: “There are people who are (as it were) keys to good and locks against evil. And there are others who are keys to evil and locks against good. Blessed are those into whose hands Allah the Exalted has placed the keys of good! And woe to those into whose hands Allah the Exalted has placed the keys of evil!”",
    "Ibn Majah, Sünnet, 19",
    "Good Character · Being a Key to Good and a Lock against Evil",
  ),
  Hadith(
    "İbn Ömer’den rivayet edildiğine göre, Resûlullah (sav), Mekke’nin fethi günü insanlara hitap ederek şöyle buyurmuştur: “Ey İnsanlar! Allah sizden câhiliye gururunu ve atalarla övünme âdetini gidermiştir. İnsanlar iki gruptur: İyi, takva sahibi, Allah katında değerli kişi ve günahkâr, bedbaht Allah katında değersiz kişi. İnsanlar, Âdem’in çocuklarıdır ve Allah, Âdem’i topraktan yaratmıştır…”",
    "Tirmizî, Tefsîrü’l-Kur’ân, 49; Ebû Dâvûd, Edeb, 110, 111",
    "Güzel Ahlak · Takva",
    "It is narrated from Ibn Umar that on the day of the conquest of Mecca the Messenger of Allah (peace be upon him) addressed the people, saying: “O people! Allah has removed from you the arrogance of the Age of Ignorance and the custom of boasting about ancestors. People are of two kinds: the righteous, God-conscious person who is honored in the sight of Allah, and the sinful, wretched person who is lowly in the sight of Allah. People are the children of Adam, and Allah created Adam from dust…”",
    "Tirmidhi, Tefsîrü’l-Kur’ân, 49; Abu Dawud, Edeb, 110, 111",
    "Good Character · God-Consciousness",
  ),
  Hadith(
    "Abdullah (b. Mes’ûd) tarafından nakledildiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Doğruluktan ayrılmayın. Çünkü doğruluk (insanı) iyiliğe, iyilik de cennete götürür. Kişi devamlı doğru söyler ve doğruluktan ayrılmazsa Allah katında “doğru/sıddîk” olarak tescillenir. Yalandan sakının! Çünkü yalan (insanı) kötülüğe, kötülük de cehenneme götürür. Kişi devamlı yalan söyler, yalan peşinde koşarsa Allah katında “yalancı/kezzâb” olarak tescillenir.”",
    "Müslim, Birr, 105",
    "Güzel Ahlak · Doğruluk ve Yalancılık",
    "It is narrated by Abdullah (ibn Mas’ud) that the Messenger of Allah (peace be upon him) said: “Hold fast to truthfulness, for truthfulness leads (a person) to righteousness, and righteousness leads to Paradise. A person keeps speaking the truth and holding to truthfulness until he is recorded with Allah as ‘truthful’ (siddiq). Beware of lying, for lying leads (a person) to wickedness, and wickedness leads to Hell. A person keeps lying and pursuing falsehood until he is recorded with Allah as ‘a liar’ (kadhdhab).”",
    "Muslim, Birr, 105",
    "Good Character · Truthfulness and Lying",
  ),
  Hadith(
    "Abdullah b. Ömer’in naklettiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Allah için size sığınan kimseye sığınak olun. Allah için isteyen kimseye verin. Sizi davet edene icabet edin, size bir iyilik yapana karşılığını verin. Eğer onun karşılığını verecek bir şey bulamazsanız, karşılıkta bulunduğunuza kanaat getirinceye kadar ona dua edin.”",
    "Ebû Dâvûd, Zekât, 38",
    "Sosyal Hayat · İnsanlara İyilikle Muamele",
    "Abdullah ibn Umar narrated that the Messenger of Allah (peace be upon him) said: “Give refuge to whoever seeks refuge with you for the sake of Allah. Give to whoever asks of you for the sake of Allah. Accept the invitation of whoever invites you, and repay whoever does you a kindness. If you cannot find anything with which to repay him, then pray for him until you feel that you have repaid him.”",
    "Abu Dawud, Zekât, 38",
    "Social Life · Treating People with Kindness",
  ),
  Hadith(
    "Ebû Musa’dan nakledildiğine göre, Hz. Peygamber (sav) şöyle buyurmuştur: “İyi arkadaşla kötü arkadaş misk taşıyan kimse ile körük üfüren kimse gibidir. Misk taşıyan ya sana onu ikram eder yahut sen ondan (miski) satın alırsın ya da ondan güzel bir koku duyarsın. Körük üfüren kimse ise ya elbiseni yakar ya da ondan kötü bir koku duyarsın!”",
    "Müslim, Birr, 146; Buhârî, Sayd, 31",
    "Sosyal Hayat · İyi Arkadaş - Kötü Arkadaş",
    "It is narrated from Abu Musa that the Prophet (peace be upon him) said: “The good companion and the bad companion are like one who carries musk and one who blows a blacksmith’s bellows. The one carrying musk will either offer you some, or you will buy (musk) from him, or at least you will enjoy a pleasant scent from him. As for the one blowing the bellows, he will either burn your clothes or you will get a foul smell from him!”",
    "Muslim, Birr, 146; Bukhari, Sayd, 31",
    "Social Life · The Good Companion and the Bad Companion",
  ),
  Hadith(
    "Ebû Hüreyre’den nakledildiğine göre, Hz. Peygamber (sav) şöyle buyurmuştur: “Devlet otoritesi en büyük hamidir. Haksızlıklarla onun vasıtasıyla (yani hukuk yoluyla) mücadele edilir ve onun vasıtasıyla (tehlikelerden) korunulur. Şayet bu otoriteyi kullanan(lar), Allah’tan sakınmayı emreder ve adaletle hükmeder(ler)se bu yaptıklarından sevap kazanır(lar). Bunun aksine davranır(lar)sa (vebalini) çeker(ler).”",
    "Müslim, İmâre, 43",
    "Sosyal Hayat · Devlet Otoritesi ve Adalet",
    "It is narrated from Abu Hurairah that the Prophet (peace be upon him) said: “State authority is the greatest protector. Injustices are fought through it (that is, through the rule of law), and through it people are protected (from dangers). If those who wield this authority command the fear of Allah and rule with justice, they earn reward for what they do. If they act otherwise, they bear (the burden of) it.”",
    "Muslim, İmâre, 43",
    "Social Life · State Authority and Justice",
  ),
  Hadith(
    "Ebû Saîd el-Hudrî’nin naklettiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Altına karşılık altın, gümüşe karşılık gümüş, buğdaya karşılık buğday, arpaya karşılık arpa, hurmaya karşılık hurma, tuza karşılık tuz, eşit miktarda ve peşin olarak satılır. Her kim daha fazla verir veya alırsa muhakkak faiz uygulaması yapmıştır. Alanla veren bu hususta eşittir.”",
    "Müslim, Müsâkât, 82",
    "Sosyal Hayat · Faiz",
    "Abu Said al-Khudri narrated that the Messenger of Allah (peace be upon him) said: “Gold for gold, silver for silver, wheat for wheat, barley for barley, dates for dates, and salt for salt are to be sold in equal amounts and hand to hand. Whoever gives more or takes more has engaged in usury. The one who takes and the one who gives are equal in this.”",
    "Muslim, Müsâkât, 82",
    "Social Life · Usury",
  ),
  Hadith(
    "Câbir b. Abdullah’ın naklettiğine göre, Resûlullah (sav) şöyle buyurmuştur: “Ey insanlar! Allah’tan (hakkıyla) sakının ve (rızkınızı) ararken güzel yollarla arayın. Zira hiç kimse, rızkını elde etmeden ölmeyecektir, gecikse bile (rızkına kavuşacaktır). Allah’tan (hakkıyla) sakının ve (rızkınızı) ararken güzel yollarla arayın. Helâl olanı alın, haram olanı terk edin.”",
    "İİbn Mâce, Ticâret, 2",
    "Sosyal Hayat · Rızık",
    "Jabir ibn Abdullah narrated that the Messenger of Allah (peace be upon him) said: “O people! Fear Allah (as He deserves) and seek (your provision) in good ways. For no one will die until he has received his provision, even if it is delayed. Fear Allah (as He deserves) and seek (your provision) in good ways. Take what is lawful and leave what is forbidden.”",
    "Ibn Majah, Ticâret, 2",
    "Social Life · Sustenance",
  ),
  Hadith(
    "Ebû Hüreyre’den nakledildiğine göre, bir gün Resûlullah (sav), “Müflis kimdir, biliyor musunuz?” diye sordu. Ashâbı, “Bize göre müflis, parası ve malı olmayan kimsedir.” dediler. Bunun üzerine Hz. Peygamber, “Şüphesiz ki ümmetimin müflisi, kıyamet günü namaz, oruç ve zekâtla gelir. Aynı zamanda şuna sövmüş, buna iftira etmiş, şunun malını yemiş, bunun kanını dökmüş ve şunu dövmüş bir hâlde gelir. Bunun üzerine iyiliklerinin sevabı şuna buna verilir. Üzerindeki kul hakları bitmeden sevapları biterse, hak sahiplerinin günahları kendisine yüklenir. Sonra da cehenneme atılır.” buyurdu.",
    "Müslim, Birr, 59",
    "Sosyal Hayat",
    "It is narrated from Abu Hurairah that one day the Messenger of Allah (peace be upon him) asked, “Do you know who the bankrupt one is?” His Companions said, “Among us, the bankrupt one is the person who has neither money nor property.” Thereupon the Prophet said, “Indeed, the bankrupt one of my community is the one who comes on the Day of Resurrection with prayer, fasting and zakat, but who also comes having insulted this one, slandered that one, consumed the wealth of this one, shed the blood of that one, and beaten another. Then the reward of his good deeds is given to this one and that one. If his good deeds run out before the rights he owes to others are settled, the sins of those he wronged are loaded onto him. Then he is thrown into Hell.”",
    "Muslim, Birr, 59",
    "Social Life",
  ),
];
